[[intervals]]
  notation = "♭2[-11]"
  interval = "Δ3/♭3"
  ratio = "20/19"
  cents = 88.80

[[intervals]]
  notation = "♭2[-6]"
  interval = "♭3/Δ2"
  ratio = "19/18"
  cents = 93.60

[[intervals]]
  notation = "♭2[-1]"
  interval = "Δ2/♭2"
  ratio = "18/17"
  cents = 98.95

[[intervals]]
  notation = "♭2[+5]"
  interval = "♭2/P1"
  ratio = "17/16"
  cents = 104.96

[[intervals]]
  notation = "♭2[+12]"
  interval = "P8/Δ7"
  ratio = "16/15"
  cents = 111.73

[[intervals]]
  notation = "♭2[+19]"
  interval = "Δ7/♭7"
  ratio = "15/14"
  cents = 119.44

[[intervals]]
  notation = "♭2[+28]"
  interval = "♭7/♮6"
  ratio = "14/13"
  cents = 128.30

[[intervals]]
  notation = "♭2[+39]"
  interval = "♮6/P5"
  ratio = "13/12"
  cents = 138.57

[[intervals]]
  notation = "Δ2[-49]"
  interval = "P5/♯4"
  ratio = "12/11"
  cents = 150.64

[[intervals]]
  notation = "Δ2[-35]"
  interval = "♯4/Δ3"
  ratio = "11/10"
  cents = 165.00

[[intervals]]
  notation = "Δ2[-27]"
  interval = "♮4/♭3"
  ratio = "21/19"
  cents = 173.27

[[intervals]]
  notation = "Δ2[-18]"
  interval = "Δ3/Δ2"
  ratio = "10/9"
  cents = 182.40

[[intervals]]
  notation = "Δ2[-7]"
  interval = "♭3/♭2"
  ratio = "19/17"
  cents = 192.55

[[intervals]]
  notation = "Δ2[+4]"
  interval = "Δ2/P1"
  ratio = "9/8"
  cents = 203.91

[[intervals]]
  notation = "Δ2[+17]"
  interval = "♭9/Δ7"
  ratio = "17/15"
  cents = 216.69

[[intervals]]
  notation = "Δ2[+31]"
  interval = "P8/♭7"
  ratio = "8/7"
  cents = 231.17

[[intervals]]
  notation = "Δ2[+48]"
  interval = "Δ7/♮6"
  ratio = "15/13"
  cents = 247.74
