[[intervals]]
  notation = "4[-46]"
  interval = "♮6/Δ3"
  ratio = "13/10"
  cents = 454.21

[[intervals]]
  notation = "4[-36]"
  interval = "♭9/♮6"
  ratio = "17/13"
  cents = 464.43

[[intervals]]
  notation = "4[-29]"
  interval = "♮4/P1"
  ratio = "21/16"
  cents = 470.78

[[intervals]]
  notation = "4[-2]"
  interval = "P8/P5"
  ratio = "4/3"
  cents = 498.04

[[intervals]]
  notation = "4[+37]"
  interval = "Δ7/♯4"
  ratio = "15/11"
  cents = 536.95

[[intervals]]
  notation = "♯4[-49]"
  interval = "♯4/P1"
  ratio = "11/8"
  cents = 551.32

[[intervals]]
  notation = "♯4[-37]"
  interval = "Δ2/♮6"
  ratio = "18/13"
  cents = 563.38

[[intervals]]
  notation = "♯4[-17]"
  interval = "♭7/Δ3"
  ratio = "7/5"
  cents = 582.51

[[intervals]]
  notation = "♯4[+17]"
  interval = "Δ10/♭7"
  ratio = "10/7"
  cents = 617.49

[[intervals]]
  notation = "♯4[+49]"
  interval = "P8/♯4"
  ratio = "16/11"
  cents = 648.68
