[[intervals]]
  notation = "♭6[-35]"
  interval = "♭7/Δ2"
  ratio = "14/9"
  cents = 764.92

[[intervals]]
  notation = "♭6[-18]"
  interval = "♯11/♭7"
  ratio = "11/7"
  cents = 782.49

[[intervals]]
  notation = "♭6[+14]"
  interval = "P8/Δ3"
  ratio = "8/5"
  cents = 813.69

[[intervals]]
  notation = "♭6[+41]"
  interval = "♮6/P1"
  ratio = "13/8"
  cents = 840.53

[[intervals]]
  notation = "Δ6[-47]"
  interval = "Δ2/♯4"
  ratio = "18/11"
  cents = 852.59

[[intervals]]
  notation = "Δ6[-16]"
  interval = "Δ10/P5"
  ratio = "5/3"
  cents = 884.36

[[intervals]]
  notation = "Δ6[+33]"
  interval = "Δ12/♭7"
  ratio = "12/7"
  cents = 933.13
