[7-tone]
lyd = [0, 2, 4, 6, 7, 9, 11]
maj = [0, 2, 4, 5, 7, 9, 11]
mix = [0, 2, 4, 5, 7, 9, 10]
dor = [0, 2, 3, 5, 7, 9, 10]
min = [0, 2, 3, 5, 7, 8, 10]
phr = [0, 1, 3, 5, 7, 8, 10]
loc = [0, 1, 3, 5, 6, 8, 10]

[6-tone]
lyd-maj = [0, 2, 4, *, 7, 9, 11]
maj-mix = [0, 2, 4, 5, 7, 9, *]
mix-dor = [0, 2, *, 5, 7, 9, 10]
dor-min = [0, 2, 3, 5, 7, *, 10]
min-phr = [0, *, 3, 5, 7, 8, 10]
phr-loc = [0, 1, 3, 5, *, 8, 10]


[5-tone]
lyd-maj-mix = [0, 2, 4, *, 7, 9, *]
maj-mix-dor = [0, 2, *, 5, 7, 9, *]
mix-dor-min = [0, 2, *, 5, 7, *, 10]
dor-min-phr = [0, *, 3, 5, 7, *, 10]
min-phr-loc = [0, *, 3, 5, *, 8, 10]
