[8-tone]
bebop-dominant = [0, 2, 4, 5, 7, 9, 10, 11]
bebop-dorian = [0, 2, 3, 4, 5, 7, 9, 10]
bebop-major = [0, 2, 4, 5, 7, 8, 9, 11]
bebop-melodic-minor = [0, 2, 3, 5, 7, 8, 9, 11]
bebop-harmonic-minor = [0, 2, 3, 5, 7, 8, 10, 11]

[7-tone]
lydian-dominant = [0, 2, 4, 6, 7, 9, 10]
harmonic-major = [0, 2, 4, 5, 7, 8, 11]
melodic-minor = [0, 2, 3, 5, 7, 9, 11]
harmonic-minor = [0, 2, 3, 5, 7, 8, 11]
half-diminished = [0, 2, 3, 5, 6, 8, 10]
super-locrian = [0, 1, 3, 4, 6, 8, 10]
enigmatic = [0, 1, 4, 6, 8, 10, 11]