[[8-tone]]

[arabic]

maqam-hijaz = [0, 1, 4, 5, 7, 8, 10, 11]
maqam-shadd-araban = [0, 1, 3, 4, 5, 6, 9, 10]
maqam-nahawand = [0, 2, 3, 5, 7, 8, 10, 11]

[jewish]

magen-abot-1 = [0, 1, 3, 4, 6, 8, 10, 11]
magen-abot-2 = [0, 1, 3, 4, 6, 8, 9, 11]
adonai-malakh = [0, 1, 2, 3, 5, 7, 9, 10]

[exoticisms]

algerian = [0, 2, 3, 5, 6, 7, 8, 11]
spanish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10]


[[7-tone]]

[hindustani]

marva-thaat = [0, 1, 4, 6, 7, 9, 11]
poorvi-thaat = [0, 1, 4, 6, 7, 8, 11]
todi-thaat = [0, 1, 3, 6, 7, 8, 11]
bhairav-thaat = [0, 1, 4, 5, 7, 8, 11]

[eastern-european]

moravian-pistalkova = [0, 2, 3, 5, 6, 8, 9]


[[6-tone]]

[ethiopian]

sabai-silt = [0, 1, 3, 5, 7, 10]


[[5-tone]]

[chinese]

chaio = [0, 2, 5, 8, 10]
kung = [0, 2, 4, 6, 9]

[korean]

kyemyonjo = [0, 3, 5, 7, 9]
nando-kyemyonjo = [0, 2, 3, 5, 7]

[japanese]

han-kumoi = [0, 2, 5, 7, 8]
hon-kumoi-joshi = [0, 1, 5, 7, 8]
kokin-joshi = [0, 1, 5, 7, 10]
iwato = [0, 1, 5, 6, 10]

[ethiopian]

batti-major-sharp-5 = [0, 4, 5, 8, 11]
batti-mineur = [0, 3, 6, 7, 11]
anchihoye = [0, 1, 5, 6, 9]
