[8-tone]
whole-half-dim = [0, 2, 3, 5, 6, 8, 9, 11]
half-whole-dim = [0, 1, 3, 4, 6, 7, 9, 10]

[6-tone]
augmented = [0, 3, 4, 7, 8, 11]
whole-tone = [0, 2, 4, 6, 8, 10]
tritone = [0, 1, 4, 6, 7, 10]
two-semitone-tritone = [0, 1, 2, 6, 7, 8]

