[[10-tone]]

[blues]
lyd-ion-mix-dor = [0, 2, 3, 4, 5, 6, 7, 9, 10, 11]

[major-minor]
ion-aeo = [0, 2, 3, 4, 5, 7, 8, 9, 10, 11]


[[9-tone]]

[blues]
ion-mix-dor = [0, 2, 3, 4, 5, 7, 9, 10, 11]
mix-dor-add-lyd-4 = [0, 2, 3, 4, 5, 6, 7, 9, 10]


[[8-tone]]

[bebop]
ion-mix = [0, 2, 4, 5, 7, 9, 10, 11]
mix-dor = [0, 2, 3, 4, 5, 7, 9, 10]
ion-add-aeo-6 = [0, 2, 4, 5, 7, 8, 9, 11]
ion-flat-3-add-aeo-6 = [0, 2, 3, 5, 7, 8, 9, 11]
aeo-add-ion-7 = [0, 2, 3, 5, 7, 8, 10, 11]

[[7-tone]]

[harmonic-major]
lyd-sharp-2-sharp-5 = [0, 3, 4, 6, 8, 9, 11]
lyd-flat-3 = [0, 2, 3, 6, 7, 9, 11]
ion-flat-6 = [0, 2, 4, 5, 7, 8, 11]
mix-flat-2 = [0, 1, 4, 5, 7, 9, 10]
dor-flat-5 = [0, 2, 3, 5, 6, 9, 10]
phr-flat-4 = [0, 1, 3, 4, 7, 8, 10]
loc-double-flat-7 = [0, 1, 3, 5, 6, 8, 9]

[harmonic-minor]
lyd-sharp-2 = [0, 3, 4, 6, 7, 9, 11]
lyd-flat-3-flat-7 = [0, 2, 3, 6, 7, 9, 10]
ion-sharp-5 = [0, 2, 4, 5, 8, 9, 11]
ion-flat-3-flat-6 = [0, 2, 3, 5, 7, 8, 11]
mix-flat-2-flat-6 = [0, 1, 4, 5, 7, 8, 10]
dor-flat-2-flat-5 = [0, 1, 3, 5, 6, 9, 10]
loc-flat-4-double-flat-7 = [0, 1, 3, 4, 6, 8, 9]

[melodic-minor]
lyd-sharp-5 = [0, 2, 4, 6, 8, 9, 11]
lyd-flat-7 = [0, 2, 4, 6, 7, 9, 10]
ion-flat-3 = [0, 2, 3, 5, 7, 9, 11]
mix-flat-6 = [0, 2, 4, 5, 7, 8, 10]
dor-flat-2 = [0, 1, 3, 5, 7, 9, 10]
aeo-flat-5 = [0, 2, 3, 5, 6, 8, 10]
loc-flat-4 = [0, 1, 3, 4, 6, 8, 10]


[[6-tone]]

[major-blues]
lyd-ion-mix-add-dor-3 = [0, 2, 3, 4, 7, 9]

[minor-blues]
dor-aeo-phr-add-loc-5 = [0, 3, 5, 6, 7, 10]