[[modes]]
  slug = "lyd-x3-x6"
  canonical = "Lydian (drop 3/6)"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = []
    4 = [1]
    5 = [1]
    6 = []
    7 = [1]

  [modes.names]
    Carnatic = "Hamsanādam Rāgam"

[[modes]]
  slug = "ion-x2-x6"
  canonical = "Ionian (drop 2/6)"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [1]
    4 = [0]
    5 = [1]
    6 = []
    7 = [1]

  [modes.names]
    Ethiopian = "Bati [Batti] Major"
    Carnatic = "Gambhiranata Rāgam"
    Japanese = "Ryu-kyu"

[[modes]]
  slug = "mix-x2-x5"
  canonical = "Mixolydian (drop 2/5)"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [1]
    4 = [0]
    5 = []
    6 = [1]
    7 = [0]

  names = {}
