[[modes]]
  slug = "aeo-x4-x6"
  canonical = "Aeolian (drop 4/6)"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = []
    5 = [1]
    6 = [0]
    7 = []

  [modes.names]
    Ethiopian = "Half Tizita (Tezita), Tizita Minor"

[[modes]]
  slug = "phr-x3-x7"
  canonical = "Phrygian (drop 3/7)"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = []
    4 = [0]
    5 = [1]
    6 = [0]
    7 = []

  [modes.names]
    Ethiopian = "Ambassel"
    Carnatic = "Karnataka Shuddha (Śuddha) Sāveri Rāgam, Asāvēri Rāgam (ascending)"
    Japanese = "In"

[[modes]]
  slug = "loc-x3-x6"
  canonical = "Locrian (drop 3/6)"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = []
    4 = [0, 1]
    5 = []
    6 = []
    7 = [0]

  [modes.names]
    Ethiopian = "Anchihoye"
