[[modes]]
  slug = "lyd-x2-x6"
  canonical = "Lydian (drop 2/6)"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [1]
    4 = [1]
    5 = [1]
    6 = []
    7 = [1]

  [modes.names]
    Ethiopian = "Bati (Batti) Lydian"
    Carnatic = "Amritavarshini (Amr̥tavarṣiṇi) Rāgam"

[[modes]]
  slug = "ion-x2-x5"
  canonical = "Ionian (drop 2/5)"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [1]
    4 = [0]
    5 = []
    6 = [1]
    7 = [1]

  [modes.names]
    Hindustani = "Raag Bhinna Shadja"
