[[modes]]
  slug = "phr-x4-x7"
  canonical = "Phrygian (drop 4/7)"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = []
    5 = [1]
    6 = [0]
    7 = []

  [modes.names]
    Carnatic = "Bhūpalam Rāgam"
    Hindustani = "Raag Bhoopal (Bhupal) Todi"

[[modes]]
  slug = "loc-x3-x7"
  canonical = "Locrian (drop 3/7)"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = []
    4 = [0, 1]
    5 = []
    6 = [0]
    7 = []

  names = {}
