[[modes]]
  slug = "dor-x4-x7"
  canonical = "Dorian (drop 4/7)"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = []
    5 = [1]
    6 = [1]
    7 = []

  [modes.names]
    Carnatic = "Shivaranjani (Śivaranjani) Rāgam"
    Hindustani = "Raag Shivaranjani"

[[modes]]
  slug = "aeo-x3-x7"
  canonical = "Aeolian (drop 3/7)"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = []
    4 = [0]
    5 = [1]
    6 = [0]
    7 = []

  names = {}

[[modes]]
  slug = "phr-x3-x6"
  canonical = "Phrygian (drop 3/6)"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = []
    4 = [0]
    5 = [1]
    6 = []
    7 = [0]

  [modes.names]
    Carnatic = "Revati Rāgam"
    Hindustani = "Raag Bairagi (Bairagi Bhairav)"

[[modes]]
  slug = "loc-x2-x6"
  canonical = "Locrian (drop 2/6)"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [0]
    4 = [0, 1]
    5 = []
    6 = []
    7 = [0]

  names = {} 
