[[modes]]
  slug = "lyd-x2-x5"
  canonical = "Lydian (drop 2/5)"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [1]
    4 = [1]
    5 = []
    6 = [1]
    7 = [1]

  [modes.names]
    Carnatic = "Sunādavinodini Rāgam"
