[[modes]]
  ordinal = 1
  slug = "lyd-ion-mix"
  canonical = "Lydian/Ionian/Mixolydian Pentatonic"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = []
    5 = [1]
    6 = [1]
    7 = []

  [modes.names]
    Western = "Major Pentatonic"
    Ethiopian = "Full Tizita [Tezita], Tizita Major"
    Hindustani = "Raag Bhoopali [Bhoop, Bhupālī]"
    Carnatic = "Mohanam Rāgam"
    Chinese = "Gong"
    Japanese = "Ryo, Yo (C mode)"

[[modes]]
  ordinal = 2
  slug = "ion-mix-dor"
  canonical = "Ionian/Mixolydian/Dorian Pentatonic"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = []
    4 = [0]
    5 = [1]
    6 = [1]
    7 = []

  [modes.names]
    Western = "Scottish Pentatonic"
    Hindustani = "Raag Durga"
    Carnatic = "Śuddha Sāveri Rāgam"
    Chinese = "Zhi"
    Korean = "Pyeongjo [P’yŏngjo]"
    Japanese = "Ritsu, Yo (G mode)"
    Vietnamese = "Bac"

[[modes]]
  ordinal = 3
  slug = "mix-dor-aeo"
  canonical = "Mixolydian/Dorian/Aeolian Pentatonic"
  quality = "major-minor"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = []
    4 = [0]
    5 = [1]
    6 = []
    7 = [0]

  [modes.names]
    Ethiopian = "Yematebela Wofe"
    Hindustani = "Raag Madhumad Sarang"
    Carnatic = "Madhyamāvati Rāgam"
    Chinese = "Shang"
    Japanese = "Yo (D mode)"

[[modes]]
  ordinal = 4
  slug = "dor-aeo-phr"
  canonical = "Dorian/Aeolian/Phrygian Pentatonic"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [0]
    4 = [0]
    5 = [1]
    6 = []
    7 = [0]

  [modes.names]
    Western = "Minor Pentatonic"
    Ethiopian = "Bati [Batti] Minor"
    Hindustani = "Raag Dhani"
    Carnatic = "Udayaravichandrika Rāgam, Śuddha Dhanyasi Rāgam"
    Chinese = "Yu"
    Korean = "Gyemyeonjo [Kyemyŏnjo]"
    Japanese = "Min-yo [Min'yō], Yo (A mode)"

[[modes]]
  ordinal = 5
  slug = "aeo-phr-loc"
  canonical = "Aeolian/Phrygian/Locrian Pentatonic"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [0]
    4 = [0]
    5 = []
    6 = [0]
    7 = [0]

  [modes.names]
    Ethiopian = "Shegaye"
    Hindustani = "Raag Malkauns"
    Carnatic = "Hindōḷaṃ Rāgam"
    Chinese = "Jue"
    Japanese = "Yo (E mode)"
