[[divisions]]
  [[divisions.intervals]]
    name = "perfect fifth"
    degree = "5"
    ratio = "3/2"
    cents = 701.96

  [[divisions.intervals]]
    name = "perfect fourth"
    degree = "4"
    ratio = "4/3"
    cents = 498.04

[[divisions]]
  [[divisions.intervals]]
    name = "grave fifth"
    degree = "5"
    ratio = "40/27"
    cents = 680.45

  [[divisions.intervals]]
    name = "acute fourth"
    degree = "4"
    ratio = "27/20"
    cents = 519.55

[[divisions]]
  [[divisions.intervals]]
    name = "classic diminished fifth"
    degree = "4s"
    ratio = "36/25"
    cents = 631.29

  [[divisions.intervals]]
    name = "classic augmented fourth"
    degree = "4s"
    ratio = "25/18"
    cents = 568.72

[[divisions]]
  [[divisions.intervals]]
    name = "diminished fifth"
    degree = "4s"
    ratio = "64/45"
    cents = 609.78

  [[divisions.intervals]]
    name = "augmented fourth"
    degree = "4s"
    ratio = "45/32"
    cents = 590.22
