[degrees]
1 = [1]
2 = [1]
3 = [0]
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Western = ["Dorian/Aeolian Hexatonic", "Minor Hexatonic"]
Carnatic = ["Raga Manirangu"]
Japanese = ["Yo (auxiliary 2nd)"]
Exoticisms = ["Eskimo Hexatonic"]

[degree-rotation-from]
lyd-ion = 0
ion-mix = 0
mix-dor = 0
aeo-phr = 0
phr-loc = 0
