[degrees]
1 = [1]
2 = [1]
3 = [1]
4 = [0]
5 = [1]
6 = [1]
7 = []

[names]
Western = ["Ionian/Mixolydian Hexatonic"]
Carnatic = ["Raga Kambhoji (ascending)"]
Exoticisms = ["Scottish Hexatonic"]

[degree-rotation-from]
lyd-ion = 0
mix-dor = 0
dor-aeo = 0
aeo-phr = 0
phr-loc = 0
