[degrees]
1 = [1]
2 = [1]
3 = [1]
4 = []
5 = [1]
6 = [1]
7 = [1]

[names]
Western = ["Lydian/Ionian Hexatonic"]

[degree-rotation-from]
ion-mix = "4"
mix-dor = "b7"
dor-aeo = "b3"
aeo-phr = "b6"
phr-loc = "b2"
