[degrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = [1]
7 = [0]

[names]
Western = ["Mixolydian/Dorian Hexatonic"]
Hindustani = ["Gorakh Kalyan"]
Carnatic = ["Raga Darbar (ascending)"]

[degree-rotation-from]
lyd-ion = 0
ion-mix = 0
dor-aeo = 0
aeo-phr = 0
phr-loc = 0