[degrees]
1 = [1]
2 = [1]
3 = [0]
4 = []
5 = [1]
6 = [0]
7 = []

[names]
Western = ["Aeolian x4/x7"]
Ethiopian = ["Half Tizita", "Tizita Minor"]

[degree-rotation-from]
phr-x3-x7 = 4
ion-x2-x5 = 6
lyd-x2-x6 = 3
loc-x3-x6 = 7
