[names]
Western = "Aeolian x4/x7"
Ethiopian = "Half Tizita (Tezita), Tizita Minor"

[scaleDegrees]
1 = [1]
2 = [1]
3 = [0]
4 = []
5 = [1]
6 = [0]
7 = []

[degreeRotations]
2 = "loc-x3-x6"
3b = "ion-x2-x5"
5 = "phr-x3-x7"
6b = "lyd-x2-x6"
