[names]
Western = "Ionian x2/x5"
Hindustani = "Raag Bhinna Shadja"

[scaleDegrees]
1 = [1]
2 = []
3 = [1]
4 = [0]
5 = []
6 = [1]
7 = [1]

[degreeRotations]
3 = "phr-x3-x7"
4 = "lyd-x2-x6"
6 = "aeo-x4-x7"
7 = "loc-x3-x6"
