[degrees]
1 = [1]
2 = []
3 = [1]
4 = [0]
5 = []
6 = [1]
7 = [1]

[names]
Western = ["Ionian x2/x5"]
Carnatic = ["Raga Bhinna Shadja"]

[degree-rotation-from]
lyd-x2-x6 = 5
loc-x3-x6 = 2
phr-x3-x7 = 6
aeo-x4-x6 = 3
