[names]
Western = "Locrian x3/x6"
Ethiopian = "Anchihoye"

[scaleDegrees]
1 = [1]
2 = [0]
3 = []
4 = [0, 1]
5 = []
6 = []
7 = [0]

[degreeRotations]
2b = "ion-x2-x5"
4 = "phr-x2-x6"
4s = "lyd-x2-x6"
7b = "aeo-x4-x7"
