[degrees]
1 = [1]
2 = []
3 = [1]
4 = [1]
5 = [1]
6 = []
7 = [1]

[names]
Western = ["Lydian x2/x6"]
Ethiopian = ["Batti Lydian"]
Carnatic = ["Raga Amritavarshini"]

[degree-rotation-from]
loc-x3-x6 = 5
ion-x2-x5 = 4
phr-x3-x7 = 2
aeo-x4-x6 = 6
