[degrees]
1 = [1]
2 = [0]
3 = []
4 = [0]
5 = [1]
6 = [0]
7 = []

[names]
Western = ["Phrygian x3/x7"]
Ethiopian = ["Ambassel"]
Japanese = ["In"]
Exoticisms = ["Japanese"]

[family]
base = "phr-x3-x7"
degree = 1
