[names]
Western = "Phrygian x3/x7"
Ethiopian = "Ambassel"
Carnatic = "Karnataka Shuddha (Śuddha) Sāveri Rāgam, Asāvēri Rāgam (ascending)"
Japanese = "In"

[scaleDegrees]
1 = [1]
2 = [0]
3 = []
4 = [0]
5 = [1]
6 = [0]
7 = []

[degreeRotations]
2b = "lyd-x2-x6"
4 = "aeo-x4-x7"
5 = "loc-x3-x6"
6b = "ion-x2-x5"
