[degrees]
1 = [1]
2 = [0]
3 = []
4 = [0]
5 = [1]
6 = [0]
7 = []

[names]
Western = ["Phrygian x3/x7"]
Ethiopian = ["Ambassel"]
Carnatic = ["Karnataka Shuddha Saveri"]
Japanese = ["In"]
Exoticisms = ["Japanese"]

[degree-rotation-from]
aeo-x4-x6 = 5
loc-x3-x6 = 4
ion-x2-x5 = 3
lyd-x2-x6 = 7
