[names]
Western = "Aeolian/Phrygian/Locrian Pentatonic"
Ethiopian = "Shegaye"
Carnatic = "Hindolam (Hindōḷaṃ) Rāgam"
Hindustani = "Raag Malkauns"
Chinese = "Jue"

[scaleDegrees]
1 = [1]
2 = []
3 = [0]
4 = [0]
5 = []
6 = [0]
7 = [0]

[degreeRotations]
3b = "ion-mix-dor"
4 = "dor-aeo-phr"
6b = "lyd-ion-mix"
7b = "mix-dor-aeo"
