[degrees]
1 = [1]
2 = []
3 = [0]
4 = [0]
5 = []
6 = [0]
7 = [0]

[names]
Western = "Aeolian/Phrygian/Locrian Pentatonic"
Ethiopian = "Shegaye"
Carnatic = "Hindolam (Hindōḷaṃ) Rāgam"
Hindustani = "Raag Malkauns"
Chinese = "Jue"

[rotational-pivots]
dor-aeo-phr = 5
mix-dor-aeo = 2
ion-mix-dor = 6
lyd-ion-mix = 3
