[degrees]
1 = [1]
2 = []
3 = [0]
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Western = ["Minor Pentatonic", "Dorian/Aeolian/Phrygian"]
Ethiopian = ["Batti Minor"]
Korean = ["Kyemyonjo (proximate)"]
Japanese = ["Yo"]
Chinese = ["Yu"]
Exoticisms = ["Peruvian Pentatonic (minor)"]

[degree-rotation-from]
mix-dor-aeo = 5
aeo-phr-loc = 4
ion-mix-dor = 2
lyd-ion-mix = 6
