[degrees]
1 = [1]
2 = []
3 = [0]
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Common = "Minor Pentatonic"
Western = "Dorian/Aeolian/Phrygian Pentatonic"
Ethiopian = "Bati (Batti) Minor"
Carnatic = "Udayaravichandrika Rāgam, Shuddha (Śuddha) Dhanyasi Rāgam"
Hindustani = "Raag Dhani"
Korean = "Gyemyeonjo (Kyemyŏnjo)"
Japanese = "Yo"
Chinese = "Yu"

[rotational-pivots]
mix-dor-aeo = 5
aeo-phr-loc = 4
ion-mix-dor = 2
lyd-ion-mix = 6
