[names]
Western = "Ionian/Mixolydian/Dorian Pentatonic"
Carnatic = "Shuddha (Śuddha) Sāveri Rāgam"
Hindustani = "Raag Durga"
Vietnamese = "Bac"
Korean = "Pyeongjo (P’yŏngjo)"
Japanese = "Ritsu"
Chinese = "Zhi"

[scaleDegrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = [1]
7 = []

[degreeRotations]
2 = "dor-aeo-phr"
4 = "lyd-ion-mix"
5 = "mix-dor-aeo"
6 = "aeo-phr-loc"
