[degrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = [1]
7 = []

[names]
Western = ["Ionian/Mixolydian/Dorian"]
Vietnamese = ["Bac"]
Korean = ["Pyeongjo", "P’yŏngjo"]
Japanese = ["Ritsu"]
Chinese = ["Zhi"]
Exoticisms = ["Scottish Pentatonic"]

[degree-rotation-from]
lyd-ion-mix = 5
mix-dor-aeo = 4
aeo-phr-loc = 3
dor-aeo-phr = 7
