[degrees]
2 = 1
3 = 1
5 = 1
6 = 1

[names]
Common = "Major Pentatonic"
Western = "Lydian/Ionian/Mixolydian Pentatonic"
Ethiopian = "Full Tizita (Tezita), Tizita Major"
Carnatic = "Mohanam Rāgam"
Hindustani = "Raag Bhoopali (Bhoop, Bhupālī)"
Japanese = "Ryo"
Chinese = "Gong"

[rotational-pivots]
ion-mix-dor = 4
aeo-phr-loc = 6
dor-aeo-phr = 3
mix-dor-aeo = 7
