[degrees]
1 = [1]
2 = [1]
3 = [1]
4 = []
5 = [1]
6 = [1]
7 = []

[names]
Western = ["Major Pentatonic", "Lydian/Ionian/Mixolydian Pentatonic"]
Ethiopian = ["Full Tizita", "Tizita Major"]
Japanese = ["Ryo"]
Chinese = ["Gong"]
Exoticisms = ["Peruvian Pentatonic (major)"]

[degree-rotation-from]
ion-mix-dor = 4
aeo-phr-loc = 6
dor-aeo-phr = 3
mix-dor-aeo = 7
