[names]
Common = "Major Pentatonic"
Western = "Lydian/Ionian/Mixolydian Pentatonic"
Ethiopian = "Full Tizita (Tezita), Tizita Major"
Carnatic = "Mohanam Rāgam"
Hindustani = "Raag Bhoopali (Bhoop, Bhupālī)"
Japanese = "Ryo"
Chinese = "Gong"

[scaleDegrees]
1 = [1]
2 = [1]
3 = [1]
4 = []
5 = [1]
6 = [1]
7 = []

[degreeRotations]
2 = "mix-dor-aeo"
3 = "aeo-phr-loc"
5 = "ion-mix-dor"
6 = "dor-aeo-phr"
