[degrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Western = ["Mixolydian/Dorian/Aeolian", "Suspended Pentatonic"]
Ethiopian = ["Yematebela Wofe"]
Chinese = ["Shang"]
Exoticisms = ["Egyptian"]

[degree-rotation-from]
ion-mix-dor = 5
lyd-ion-mix = 2
aeo-phr-loc = 3
dor-aeo-phr = 7
