[degrees]
2 = 1
4 = 0
5 = 1
7 = 0

[names]
Western = "Mixolydian/Dorian/Aeolian Pentatonic"
Ethiopian = "Yematebela Wofe"
Carnatic = "Madhyamavati (Madhyamāvati) Rāgam"
Hindustani = "Raag Madhumad Sarang"
Chinese = "Shang"

[rotational-pivots]
ion-mix-dor = 5
lyd-ion-mix = 2
aeo-phr-loc = 3
dor-aeo-phr = 7
