[names]
Western = "Mixolydian/Dorian/Aeolian Pentatonic"
Ethiopian = "Yematebela Wofe"
Carnatic = "Madhyamāvati Rāgam"
Hindustani = "Raag Madhumad Sarang"
Chinese = "Shang"

[scaleDegrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = []
7 = [0]

[degreeRotations]
2 = "aeo-phr-loc"
4 = "ion-mix-dor"
5 = "dor-aeo-phr"
7b = "lyd-ion-mix"
