[[intervals]]
  symbol = "♭2[-11]"
  interval = "Δ3/♭3"
  ratio = "20/19"
  cents = 88.80

[[intervals]]
  symbol = "♭2[-6]"
  interval = "♭3/Δ2"
  ratio = "19/18"
  cents = 93.60

[[intervals]]
  symbol = "♭2[-1]"
  interval = "Δ2/♭2"
  ratio = "18/17"
  cents = 98.95

[[intervals]]
  symbol = "♭2[+5]"
  interval = "♭2/1"
  ratio = "17/16"
  cents = 104.96

[[intervals]]
  symbol = "♭2[+12]"
  interval = "8/Δ7"
  ratio = "16/15"
  cents = 111.73

[[intervals]]
  symbol = "♭2[+19]"
  interval = "Δ7/♭7"
  ratio = "15/14"
  cents = 119.44

[[intervals]]
  symbol = "♭2[+28]"
  interval = "♭7/♭6"
  ratio = "14/13"
  cents = 128.30

[[intervals]]
  symbol = "♭2[+39]"
  interval = "♭6/5"
  ratio = "13/12"
  cents = 138.57

[[intervals]]
  symbol = "Δ2[-49]"
  interval = "5/♯4"
  ratio = "12/11"
  cents = 150.64

[[intervals]]
  symbol = "Δ2[-35]"
  interval = "♯4/Δ3"
  ratio = "11/10"
  cents = 165.00

