[degrees]
1 = [1]
2 = []
3 = [1]
4 = [0]
5 = [1]
6 = []
7 = [1]

[names]
Western = ["Ionian x2/x6"]
Ethiopian = ["Batti Major"]
Carnatic = ["Raga Gambhiranata"]

[degree-rotation-from]
lyd-x3-x6 = 5
mix-x2-x5 = 4
loc-x3-x7 = 2
phr-x4-x7 = 6
