[names]
Western = "Ionian x2/x6"
Ethiopian = "Bati (Batti) Major"
Carnatic = "Gambhiranata Rāgam"

[scaleDegrees]
1 = [1]
2 = []
3 = [1]
4 = [0]
5 = [1]
6 = []
7 = [1]

[degreeRotations]
3 = "phr-x4-x7"
4 = "lyd-x3-x6"
5 = "mix-x2-x5"
7 = "loc-x3-x7"
