[names]
Western = "Lydian x3/x6"
Carnatic = "Hamsanādam Rāgam"

[scaleDegrees]
1 = [1]
2 = [1]
3 = []
4 = [1]
5 = [1]
6 = []
7 = [1]

[degreeRotations]
2 = "mix-x2-x5"
4s = "loc-x3-x7"
5 = "ion-x2-x6"
7 = "phr-x4-x7"
