[degrees]
1 = [1]
2 = [1]
3 = []
4 = [1]
5 = [1]
6 = []
7 = [1]

[names]
Western = ["Lydian x3/x6"]
Carnatic = ["Raga Hamsanadam"]

[degree-rotation-from]
loc-x3-x7 = 5
ion-x2-x6 = 4
phr-x4-x7 = 2
mix-x2-x5 = 7
