[names]
Western = "Phrygian x4/x7"
Carnatic = "Bhūpalam Rāgam"
Hindustani = "Raag Bhoopal (Bhupal) Todi"

[scaleDegrees]
1 = [1]
2 = [0]
3 = [0]
4 = []
5 = [1]
6 = [0]
7 = []

[degreeRotations]
2b = "lyd-x2-x6"
3b = "mix-x2-x5"
5 = "loc-x3-x7"
6b = "ion-x2-x6"
