[7-tone]
maqam-nikriz = "lyd-dor-3-mix-7"
maqam-nawa-athar = "lyd-dor-3-aeo-6"
maqam-athar-kurd = "lyd-phr-2-dor-3-aeo-6"
maqam-ajam-ushayran = "ion"
maqam-shawq-afza = "ion-aeo-6"
maqam-hijazkar = "ion-phr-2-aeo-6"
maqam-zanjaran = "ion-phr-2-mix-7"
maqam-nahawand-murassa = "dor-loc-5"
maqam-kurd = "phr"

[8-tone]
maqam-mustaar = "lyd-sharp-2-add-phr-2"
maqam-huzam = "ion-add-phr-2"
maqam-ajam = "ion-add-mix-7"
maqam-hijaz = "ion-phr-2-mix-7-add-aeo-6"
maqam-awj-iraq = "ion-drop-5-add-phr-2-add-aeo-6"
maqam-mahur = "ion-add-dor-3"
maqam-suznak = "ion-aeo-6-add-dor-3"
maqam-suzdalara = "dor-add-ion-3"
maqam-ushaq-masri = "dor-add-aeo-6"
maqam-nahawand = "aeo-add-ion-7"
maqam-bayati-shuri = "dor-loc-5-add-phr-2"

[9-tone]
maqam-iraq = "lyd-add-phr-2-add-ion-4"
maqam-sikah = "lyd-add-phr-2-add-aeo-6"
maqam-rast = "dor-add-ion-3-add-ion-7"
maqam-nairuz = "dor-add-ion-3-add-aeo-6"
maqam-bayati = "dor-add-phr-2-add-aeo-6"
maqam-hijazkar-kurd = "phr-add-ion-3-add-ion-7"

[10-tone]
maqam-bastanikar = "lyd-aeo-6-add-phr-2-add-dor-3-add-ion-4"
maqam-dalanshin = "dor-add-phr-2-add-ion-3-add-ion-7"
