[7-tone]
maqam-shawq-afza = "ion-aeo-6"

[8-tone]
maqam-ajam = "ion-add-mix-7"
maqam-bayati-shuri = "dor-flat-5-add-phr-2"
maqam-hijaz = "phr-ion-3-add-ion-6"

[9-tone]
maqam-bayati = "dor-add-phr-2-add-aeo-6"