[5-tone]
major-pentatonic = "lyd/ion/mix"
dominant-pentatonic = "mix-drop-4-drop-6"
dorian-pentatonic = "dor-drop-2-drop-7"
minor-pentatonic = "dor/aeo/phr"

[6-tone]
blues-major = "major-pentatonic-add-dor-3"
blues-dominant = "dominant-pentatonic-add-dor-3"
blues-dorian = "dorian-pentatonic-add-ion-3"
blues-minor = "minor-pentatonic-add-loc-5"
whole-tone = "lyd-aeo-6-mix-7-drop-5"
augmented = "lyd-sharp-2-aeo-6-drop-5"
tritone = "lyd-phr-2-mix-7-drop-6"
two-semitone-tritone = "lyd-aeo-6-drop-3-drop-7-add-phr-2"

[7-tone]
blues-major = "major-pentatonic-add-dor-3-add-aeo-6"
blues-dominant = "dominant-pentatonic-add-dor-3-add-ion-7"
blues-dorian = "dorian-pentatonic-add-ion-3-add-aeo-6"
blues-minor-3-5 = "minor-pentatonic-add-ion-3-add-loc-5"
blues-minor-5-7 = "minor-pentatonic-add-loc-5-add-ion-7"
melodic-minor = "dor-ion-7"
jazz-minor-inverse = "dor-phr-2"
lydian-augmented = "lyd-sharp-5"
lydian-dominant = "lyd-mix-7"
melodic-major = "mix-aeo-6"
lydian-diminished = "lyd-dor-3"
half-diminished = "aeo-loc-5"
altered-dominant = "loc-flat-4"
harmonic-minor = "aeo-ion-7"
harmonic-major = "ion-aeo-6"
lydian-harmonic = "lyd-aeo-6"

[8-tone]
bebop-major = "ion-add-aeo-6"
bebop-dominant = "mix-add-ion-7"
bebop-dorian = "dor-add-ion-3"
bebop-melodic-minor ="dor-ion-7-add-aeo-6"
bebop-harmonic-minor = "aeo-add-ion-7"
whole-half-diminished = "dor-loc-5-ion-7-add-aeo-6"
half-whole-diminished = "dor-loc-2-lyd-4-add-ion-3"

[9-tone]
blues-major = "ion-add-dor-3-add-aeo-6"
blues-dominant = "mix-add-dor-3-add-ion-7"
blues-dorian = "dor-add-ion-3-add-aeo-6"
blues-minor-3-5 = "aeo-add-ion-3-add-loc-5"
blues-minor-5-7 = "aeo-add-loc-5-add-ion-7"
