[5-tone]
full-tizita = "lyd/ion/mix"
half-tizita = "aeo-drop-4-drop-7"
batti-major = "ion-drop-2-drop-6"
batti-minor = "dor/aeo/phr"
ambassel-a = "phr-drop-3-drop-7"
ambassel-b = "ion/mix/dor"
anchihoye = "loc-ion-6-drop-3-drop-7"
yematebela-wofe = "mix/dor/aeo"
shegaye = "aeo/phr/loc"

[6-tone]
hareri-a = "phr-drop-5-drop-6-add-ion-3"
hareri-b = "aeo-ion-7"
