[7-tone]
bilaval = "ion"
khamaj = "mix"
kafi = "dor"
asavari = "aeo"
bhairavi = "phr"
kalyan = "lyd"
marva = "lyd-phr-2"
poorvi = "lyd-phr-2-aeo-6"
todi = "lyd-phr-2-dor-3-aeo-6"
bhairav = "ion-phr-2-aeo-6"
