[7-tone]
bilaval-thaat = "ion"
khamaj-thaat = "mix"
kafi-thaat = "dor"
asavari-thaat = "aeo"
bhairavi-thaat = "phr"
kalyan-thaat = "lyd"
marva-thaat = "lyd-phr-2"
poorvi-thaat = "lyd-phr-2-aeo-6"
todi-thaat = "lyd-phr-2-dor-3-aeo-6"
bhairav-thaat = "ion-phr-2-aeo-6"
