[7-tone]

kalyan = "lyd"
bilaval = "ion"
khamaj = "mix"
kafi = "dor"
asavari = "aeo"
bhairavi = "phr"
marva = [0, 1, 4, 6, 7, 9, 11]
poorvi = [0, 1, 4, 6, 7, 8, 11]
todi = [0, 1, 3, 6, 7, 8, 11]
bhairav = [0, 1, 4, 5, 7, 8, 11]
