[[8-tone]]

[arabic]

maqam-hijaz = [0, 1, 4, 5, 7, 8, 10, 11]
maqam-shadd-araban = [0, 1, 3, 4, 5, 6, 9, 10]
maqam-nahawand = [0, 2, 3, 5, 7, 8, 10, 11]

[jewish]

magen-abot-1 = [0, 1, 3, 4, 6, 8, 10, 11]
magen-abot-2 = [0, 1, 3, 4, 6, 8, 9, 11]
adonai-malakh = [0, 1, 2, 3, 5, 7, 9, 10]

[exoticisms]

algerian = [0, 2, 3, 5, 6, 7, 8, 11]
spanish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10]


[[6-tone]]

[ethiopian]

sabai-silt = "phr-drop-6"


[[5-tone]]

[chinese]

chaio = "aeo-drop-3-drop-5"
kung = "lyd-drop-5-drop-7"

[korean]

kyemyonjo = "dor-drop-2-drop-7"
nando-kyemyonjo = "dor-aeo-drop-7"

[japanese]

han-kumoi = "aeo-drop-3-drop-7"
hon-kumoi-joshi = "phr-drop-3-drop-7"
kokin-joshi = "phr-drop-3-drop-6"
iwato = "loc-drop-3-drop-6"

[ethiopian]

batti-major-sharp-5 = "bhairav-drop-2-drop-5"
batti-mineur = "todi-drop-2-drop-5"
anchihoye = [0, 1, 5, 6, 9]
