[7-tone]
lyd = [0, 2, 4, 6, 7, 9, 11]
ion = [0, 2, 4, 5, 7, 9, 11]
mix = [0, 2, 4, 5, 7, 9, 10]
dor = [0, 2, 3, 5, 7, 9, 10]
aeo = [0, 2, 3, 5, 7, 8, 10]
phr = [0, 1, 3, 5, 7, 8, 10]
loc = [0, 1, 3, 5, 6, 8, 10]

[6-tone]
lyd-drop-2 = [0, 4, 6, 7, 9, 11]
lyd-drop-3 = [0, 2, 6, 7, 9, 11]
lyd/ion = [0, 2, 4, 7, 9, 11]
lyd-drop-5 = [0, 2, 4, 6, 9, 11]
lyd-drop-6 = [0, 2, 4, 6, 7, 11]
lyd-drop-7 = [0, 2, 4, 6, 7, 9]
ion-drop-2 = [0, 4, 5, 7, 9, 11]
ion-drop-3 = [0, 2, 5, 7, 9, 11]
ion-drop-5 = [0, 2, 4, 5, 9, 11]
ion-drop-6 = [0, 2, 4, 5, 7, 11]
ion/mix = [0, 2, 4, 5, 7, 9]
mix-drop-2 = [0, 4, 5, 7, 9, 10]
mix-dor = [0, 2, 5, 7, 9, 10]
mix-drop-4 = [0, 2, 4, 7, 9, 10]
mix-drop-5 = [0, 2, 4, 5, 9, 10]
mix-drop-6 = [0, 2, 4, 5, 7, 10]
dor-drop-2 = [0, 3, 5, 7, 9, 10]
dor-drop-4 = [0, 2, 3, 7, 9, 10]
dor-drop-5 = [0, 2, 3, 5, 9, 10]
dor/aeo = [0, 2, 3, 5, 7, 10]
dor-drop-7 = [0, 2, 3, 5, 7, 9]
aeo/phr = [0, 3, 5, 7, 8, 10]
aeo-drop-3 = [0, 2, 5, 7, 8, 10]
aeo-drop-4 = [0, 2, 3, 7, 8, 10]
aeo-drop-5 = [0, 2, 3, 5, 8, 10]
aeo-drop-7 = [0, 2, 3, 5, 7, 8]
phr-drop-3 = [0, 1, 5, 7, 8, 10]
phr-drop-4 = [0, 1, 3, 7, 8, 10]
phr/loc = [0, 1, 3, 5, 8, 10]
phr-drop-6 = [0, 1, 3, 5, 7, 10]
phr-drop-7 = [0, 1, 3, 5, 7, 8]
loc-drop-2 = [0, 3, 5, 6, 8, 10]
loc-drop-3 = [0, 1, 5, 6, 8, 10]
loc-drop-4 = [0, 1, 3, 6, 8, 10]
loc-drop-6 = [0, 1, 3, 5, 6, 10]
loc-drop-7 = [0, 1, 3, 5, 6, 8]

[5-tone-anhemitonic]
lyd-drop-5-drop-7 = [0, 2, 4, 6, 9]
lyd/ion/mix = [0, 2, 4, 7, 9]
ion/mix-drop-7 = [0, 2, 4, 5, 7]
ion/mix/dor = [0, 2, 5, 7, 9]
mix-drop-4-drop-7 = [0, 2, 4, 7, 10]
mix/dor/aeo = [0, 2, 5, 7, 10]
dor-drop-2-drop-7 = [0, 3, 5, 7, 9]
dor/aeo/phr = [0, 3, 5, 7, 10]
aeo-drop-3-drop-5 = [0, 2, 5, 8, 10]
aeo/phr/loc = [0, 3, 5, 8, 10]
loc-drop-2-drop-4 = [0, 3, 6, 8, 10]

[5-tone-hemitonic]
lyd/ion-drop-2 = [0, 4, 7, 9, 11]
lyd-drop-2-drop-5 = [0, 4, 6, 9, 11]
lyd-drop-2-drop-6 = [0, 4, 6, 7, 11]
lyd-drop-2-drop-7 = [0, 4, 6, 7, 9]
lyd/ion-drop-3 = [0, 2, 7, 9, 11]
lyd/ion-drop-5 = [0, 2, 4, 9, 11]
lyd/ion-drop-6 = [0, 2, 4, 7, 11]
lyd-drop-5-drop-6 = [0, 2, 4, 6, 11]
lyd-drop-6-drop-7 = [0, 2, 4, 6, 7]
ion-drop-2-drop-3 = [0, 5, 7, 9, 11]
ion-drop-2-drop-5 = [0, 4, 5, 9, 11]
ion-drop-2-drop-6 = [0, 4, 5, 7, 11]
ion/mix-drop-2 = [0, 4, 5, 7, 9]
ion/mix-drop-5 = [0, 2, 4, 5, 9]
mix/dor-drop-2 = [0, 5, 7, 9, 10]
mix/dor-drop-3 = [0, 2, 7, 9, 10]
mix-drop-2-drop-5 = [0, 4, 5, 9, 10]
mix-drop-2-drop-6 = [0, 4, 5, 7, 10]
mix/dor-drop-5 = [0, 2, 5, 9, 10]
mix-drop-5-drop-6 = [0, 2, 4, 5, 10]
dor-drop-2-drop-4 = [0, 3, 7, 9, 10]
dor-drop-2-drop-5 = [0, 3, 5, 9, 10]
dor/aeo-drop-2 = [0, 3, 5, 7, 10]
dor/aeo-drop-4 = [0, 2, 3, 7, 10]
dor-drop-4-drop-7 = [0, 2, 3, 7, 9]
dor/aeo-drop-5 = [0, 2, 3, 5, 10]
dor/aeo-drop-7 = [0, 2, 3, 5, 7]
aeo-drop-3-drop-4 = [0, 2, 7, 8, 10]
aeo-drop-3-drop-7 = [0, 2, 5, 7, 8]
aeo-drop-4-drop-5 = [0, 2, 3, 8, 10]
aeo-drop-4-drop-7 = [0, 2, 3, 7, 8]
aeo/phr-drop-3 = [0, 5, 7, 8, 10]
aeo/phr-drop-7 = [0, 3, 5, 7, 8]
phr/loc-drop-3 = [0, 1, 5, 8, 10]
phr-drop-3-drop-6 = [0, 1, 5, 7, 10]
phr-drop-3-drop-7 = [0, 1, 5, 7, 8]
phr-drop-4-drop-5 = [0, 1, 3, 8, 10]
phr-drop-4-drop-6 = [0, 1, 3, 7, 10]
phr-drop-4-drop-7 = [0, 1, 3, 7, 8]
phr/loc-drop-7 = [0, 1, 3, 5, 8]
phr-drop-6-drop-7 = [0, 1, 3, 5, 7]
loc-drop-2-drop-3 = [0, 5, 6, 8, 10]
loc-drop-2-drop-6 = [0, 3, 5, 6, 10]
loc-drop-2-drop-7 = [0, 3, 5, 6, 8]
loc-drop-3-drop-4 = [0, 1, 6, 8, 10]
loc-drop-3-drop-6 = [0, 1, 5, 6, 10]
loc-drop-3-drop-7 = [0, 1, 5, 6, 8]
