[5-tone]
lyd/ion/mix = [0, 2, 4, 7, 9]
ion/mix/dor = [0, 2, 5, 7, 9]
mix/dor/aeo = [0, 2, 5, 7, 10]
dor/aeo/phr = [0, 3, 5, 7, 10]
aeo/phr/loc = [0, 3, 5, 8, 10]

[6-tone]
lyd/ion = [0, 2, 4, 7, 9, 11]
ion/mix = [0, 2, 4, 5, 7, 9]
mix/dor = [0, 2, 5, 7, 9, 10]
dor/aeo = [0, 2, 3, 5, 7, 10]
aeo/phr = [0, 3, 5, 7, 8, 10]
phr/loc = [0, 1, 3, 5, 8, 10]

[7-tone]
lyd = [0, 2, 4, 6, 7, 9, 11]
ion = [0, 2, 4, 5, 7, 9, 11]
mix = [0, 2, 4, 5, 7, 9, 10]
dor = [0, 2, 3, 5, 7, 9, 10]
aeo = [0, 2, 3, 5, 7, 8, 10]
phr = [0, 1, 3, 5, 7, 8, 10]
loc = [0, 1, 3, 5, 6, 8, 10]
