[[10-tone]]

[blues]
lyd-ion-mix-dor = [0, 2, 3, 4, 5, 6, 7, 9, 10, 11]

[major-minor]
ion-aeo = [0, 2, 3, 4, 5, 7, 8, 9, 10, 11]


[[9-tone]]

[blues]
ion-mix-dor = [0, 2, 3, 4, 5, 7, 9, 10, 11]
mix-dor-add-lyd-4 = [0, 2, 3, 4, 5, 6, 7, 9, 10]


[[8-tone]]

[blues]
dor-add-lyd-4 = [0, 2, 3, 5, 6, 7, 9, 10]

[bebop]
ion-mix = [0, 2, 4, 5, 7, 9, 10, 11]
mix-dor = [0, 2, 3, 4, 5, 7, 9, 10]
ion-add-aeo-6 = [0, 2, 4, 5, 7, 8, 9, 11]
ion-dor-3-add-aeo-6 = [0, 2, 3, 5, 7, 8, 9, 11]
aeo-add-ion-7 = [0, 2, 3, 5, 7, 8, 10, 11]

[symmetric]
whole-half-diminished = [0, 2, 3, 5, 6, 8, 9, 11]
half-whole-diminished = [0, 1, 3, 4, 6, 7, 9, 10]

[[7-tone]]

[harmonic-major]
lyd-sharp-2-sharp-5 = [0, 3, 4, 6, 8, 9, 11]
lyd-dor-3 = [0, 2, 3, 6, 7, 9, 11]
ion-aeo-6 = [0, 2, 4, 5, 7, 8, 11]
mix-phr-2 = [0, 1, 4, 5, 7, 9, 10]
dor-loc-5 = [0, 2, 3, 5, 6, 9, 10]
loc-double-flat-7 = [0, 1, 3, 5, 6, 8, 9]
phr-flat-4 = [0, 1, 3, 4, 7, 8, 10]

[harmonic-minor]
lyd-sharp-2 = [0, 3, 4, 6, 7, 9, 11]
dor-lyd-4 = [0, 2, 3, 6, 7, 9, 10]
ion-sharp-5 = [0, 2, 4, 5, 8, 9, 11]
aeo-ion-7 = [0, 2, 3, 5, 7, 8, 11]
phr-ion-4 = [0, 1, 4, 5, 7, 8, 10]
loc-ion-6 = [0, 1, 3, 5, 6, 9, 10]
loc-flat-4-double-flat-7 = [0, 1, 3, 4, 6, 8, 9]

[melodic-minor]
lyd-sharp-5 = [0, 2, 4, 6, 8, 9, 11]
lyd-mix-7 = [0, 2, 4, 6, 7, 9, 10]
ion-dor-3 = [0, 2, 3, 5, 7, 9, 11]
mix-aeo-6 = [0, 2, 4, 5, 7, 8, 10]
dor-phr-2 = [0, 1, 3, 5, 7, 9, 10]
aeo-loc-5 = [0, 2, 3, 5, 6, 8, 10]
loc-flat-4 = [0, 1, 3, 4, 6, 8, 10]

[neapolitan-major]
lyd-sharp-5-sharp-6 = [0, 2, 4, 6, 8, 10, 11]
lyd-aeo-6-mix-7 = [0, 2, 4, 6, 7, 8, 10]
mix-lyd-4 = [0, 2, 4, 6, 8, 9, 10]
mix-loc-5-aeo-6 = [0, 2, 4, 5, 6, 8, 10]
aeo-flat-4-loc-5 = [0, 2, 3, 4, 6, 8, 10]
phr-ion-6-ion-7 = [0, 1, 3, 5, 7, 9, 11]
loc-double-flat-3-flat-4 = [0, 1, 2, 4, 6, 8, 10]

[neapolitan-minor]
lyd-sharp-6 = [0, 2, 4, 6, 7, 10, 11]
aeo-lyd-4 = [0, 2, 3, 6, 7, 8, 10]
ion-sharp-2 = [0, 3, 4, 5, 7, 9, 11]
mix-sharp-5 = [0, 2, 4, 5, 8, 9, 10]
phr-ion-7 = [0, 1, 3, 5, 7, 8, 11]
loc-ion-4 = [0, 1, 4, 5, 6, 8, 10]
loc-double-flat-3-flat-4-double-flat-7 = [0, 1, 2, 4, 6, 8, 9]

[harmonic-lydian]
lyd-sharp-2-sharp-5-sharp-6 = [0, 3, 4, 6, 8, 10, 11]
lyd-aeo-6 = [0, 2, 4, 6, 7, 8, 11]
ion-phr-2 = [0, 1, 4, 5, 7, 9, 11]
mix-loc-5 = [0, 2, 4, 5, 6, 9, 10]
phr-double-flat-7 = [0, 1, 3, 5, 7, 8, 9]
loc-double-flat-3 = [0, 1, 2, 5, 6, 8, 10]
aeo-flat-4 = [0, 2, 3, 4, 7, 8, 10]

[chromatic]
lyd-sharp-2-sharp-3-sharp-6 = [0, 3, 5, 6, 7, 10, 11]
lyd-phr-2-aeo-6 = [0, 1, 4, 6, 7, 8, 11]
ion-sharp-2-sharp-5-sharp-6 = [0, 3, 4, 5, 8, 10, 11]
ion-phr-2-loc-5 = [0, 1, 4, 5, 6, 9, 11]
phr-double-flat-3-double-flat-7 = [0, 1, 2, 5, 7, 8, 9]
loc-double-flat-3-double-flat-6 = [0, 1, 2, 5, 6, 7, 10]
aeo-flat-4-double-flat-7 = [0, 2, 3, 4, 7, 8, 9]

[chromatic-inverse]
lyd-sharp-3-sharp-6 = [0, 2, 5, 6, 7, 10, 11]
phr-lyd-4-ion-7 = [0, 1, 3, 6, 7, 8, 11]



[[6-tone]]

[major-blues]
lyd-ion-mix-add-dor-3 = [0, 2, 3, 4, 7, 9]

[minor-blues]
dor-aeo-phr-add-loc-5 = [0, 3, 5, 6, 7, 10]

[symmetric]
augmented = [0, 3, 4, 7, 8, 11]
whole-tone = [0, 2, 4, 6, 8, 10]
tritone = [0, 1, 4, 6, 7, 10]
two-semitone-tritone = [0, 1, 2, 6, 7, 8]
