[5-tone]
syrian-pentatonic = [0, 1, 4, 5, 8]
balinese = [0, 1, 3, 7, 8]
japanese-a = [0, 1, 5, 7, 8]
japanese-b = [0, 2, 5, 7, 8]
peruvian-pentatonic-a = [0, 2, 4, 7, 9]
peruvian-pentatonic-b = [0, 3, 5, 7, 10]
scottish-pentatonic = [0, 2, 5, 7, 9]
egyptian = [0, 2, 5, 7, 10]

[6-tone]
istrian = [0, 1, 3, 4, 6, 7]
scottish-hexatonic = [0, 2, 4, 5, 7, 9]
romani-hexatonic = [0, 1, 4, 5, 7, 8, 9]
romani-hexatonic-inverse = [0, 3, 4, 5, 7, 8, 11]
eskimo-hexatonic-a = [0, 2, 3, 5, 7, 10]
eskimo-hexatonic-b = [0, 2, 4, 6, 8, 11]
hawaiian = [0, 2, 3, 7, 9, 11]
ancient-chinese = [0, 2, 4, 6, 7, 9]

[7-tone]
hungarian-major-inverse = [0, 2, 3, 5, 6, 8, 9]
hungarian-minor-inverse = [0, 1, 4, 5, 6, 9, 10]
asian-a = [0, 1, 4, 5, 6, 8, 10]
arabian-b = [0, 2, 4, 5, 6, 8, 10]
peruvian-minor = [0, 2, 3, 5, 7, 8, 10]
spanish-romani = [0, 1, 4, 5, 7, 8, 10]
hindu = [0, 2, 4, 5, 7, 8, 10]
minor-romani = [0, 2, 3, 6, 7, 8, 10]
minor-romani-inverse = [0, 2, 4, 5, 6, 9, 10]
eskimo-heptatonic = [0, 2, 3, 5, 7, 9, 10]
romanian-minor = [0, 2, 3, 6, 7, 9, 10]
romanian-major = [0, 1, 4, 6, 7, 9, 10]
hungarian-major = [0, 3, 4, 6, 7, 9, 10]
persian = [0, 1, 4, 5, 6, 8, 11]
hungarian-romani = [0, 1, 3, 5, 7, 8, 11]
major-romani = [0, 1, 4, 5, 7, 8, 11]
ethiopian = [0, 2, 4, 5, 7, 8, 11]
hungarian-minor = [0, 2, 3, 6, 7, 8, 11]
hawaiian = [0, 2, 3, 5, 7, 9, 11]
hungarian-romani-inverse = [0, 1, 4, 5, 7, 9, 11]

[8-tone]
spanish = [0, 1, 3, 4, 5, 6, 8, 10]
spanish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10]
jewish = [0, 1, 2, 3, 5, 7, 9, 10]
algerian = [0, 2, 3, 5, 6, 7, 8, 11]
mongolian = [0, 2, 4, 5, 6, 7, 9, 11]
arabian-a = [0, 2, 3, 5, 6, 8, 9, 11]
chinese = [0, 2, 4, 5, 7, 9, 10, 11]

[9-tone]
moorish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10, 11]
