[5-tone]
scottish-pentatonic = "ion/mix/dor"
peruvian-pentatonic-a = "lyd/ion/mix"
peruvian-pentatonic-b = "dor/aeo/phr"
egyptian = "mix/dor/aeo"
syrian-pentatonic = "phr-ion-3-drop-5-drop-7"
japanese-a = "phr-drop-3-drop-7"
japanese-b = "aeo-drop-3-drop-7"
balinese = "phr-drop-4-drop-7"

[6-tone]
ancient-chinese = "lyd-drop-7"
scottish-hexatonic = "ion-drop-7"
eskimo-hexatonic-a = "dor/aeo"
eskimo-hexatonic-b = "lyd-aeo-6-drop-5"
hawaiian-hexatonic = "ion-dor-3-drop-4"
istrian = "lyd-phr-2-drop-6-drop-7-add-dor-3"

[7-tone]
hawaiian = [0, 2, 3, 5, 7, 9, 11]
eskimo = [0, 2, 3, 5, 7, 9, 10]
hindu = [0, 2, 4, 5, 7, 8, 10]
ethiopian = [0, 2, 4, 5, 7, 8, 11]
arabian = [0, 2, 4, 5, 6, 8, 10]
peruvian-minor = [0, 2, 3, 5, 7, 8, 10]
hungarian-minor = [0, 2, 3, 6, 7, 8, 11]
hungarian-minor-inverse = [0, 1, 4, 5, 6, 9, 10]
hungarian-major = [0, 3, 4, 6, 7, 9, 10]
hungarian-major-inverse = [0, 2, 3, 5, 6, 8, 9]
romanian-minor = [0, 2, 3, 6, 7, 9, 10]
romanian-major = [0, 1, 4, 6, 7, 9, 10]
minor-romani = [0, 2, 3, 6, 7, 8, 10]
minor-romani-inverse = [0, 2, 4, 5, 6, 9, 10]
major-romani = [0, 1, 4, 5, 7, 8, 11]
spanish-romani = [0, 1, 4, 5, 7, 8, 10]
hungarian-romani = [0, 1, 3, 5, 7, 8, 11]
hungarian-romani-inverse = [0, 1, 4, 5, 7, 9, 11]
persian = [0, 1, 4, 5, 6, 8, 11]
asian = [0, 1, 4, 5, 6, 8, 10]

[8-tone]
mongolian = [0, 2, 4, 5, 6, 7, 9, 11]
chinese = [0, 2, 4, 5, 7, 9, 10, 11]
spanish = [0, 1, 3, 4, 5, 6, 8, 10]
spanish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10]
arabian-octotonic = [0, 2, 3, 5, 6, 8, 9, 11]
algerian = [0, 2, 3, 5, 6, 7, 8, 11]
jewish = [0, 1, 2, 3, 5, 7, 9, 10]

[9-tone]
moorish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10, 11]
