[5-tone]
scottish-pentatonic = [0, 2, 5, 7, 9]
peruvian-pentatonic-a = [0, 2, 4, 7, 9]
peruvian-pentatonic-b = [0, 3, 5, 7, 10]
egyptian = [0, 2, 5, 7, 10]
syrian-pentatonic = [0, 1, 4, 5, 8]
japanese-a = [0, 1, 5, 7, 8]
japanese-b = [0, 2, 5, 7, 8]
balinese = [0, 1, 3, 7, 8]

[6-tone]
ancient-chinese = [0, 2, 4, 6, 7, 9]
scottish-hexatonic = [0, 2, 4, 5, 7, 9]
eskimo-hexatonic-a = [0, 2, 3, 5, 7, 10]
eskimo-hexatonic-b = [0, 2, 4, 6, 8, 11]
hawaiian-hexatonic = [0, 2, 3, 7, 9, 11]
romani-hexatonic = [0, 1, 4, 5, 7, 8, 9]
romani-hexatonic-inverse = [0, 3, 4, 5, 7, 8, 11]
istrian = [0, 1, 3, 4, 6, 7]

[7-tone]
hawaiian = [0, 2, 3, 5, 7, 9, 11]
eskimo = [0, 2, 3, 5, 7, 9, 10]
hindu = [0, 2, 4, 5, 7, 8, 10]
ethiopian = [0, 2, 4, 5, 7, 8, 11]
arabian = [0, 2, 4, 5, 6, 8, 10]
peruvian-minor = [0, 2, 3, 5, 7, 8, 10]
hungarian-minor = [0, 2, 3, 6, 7, 8, 11]
hungarian-minor-inverse = [0, 1, 4, 5, 6, 9, 10]
hungarian-major = [0, 3, 4, 6, 7, 9, 10]
hungarian-major-inverse = [0, 2, 3, 5, 6, 8, 9]
romanian-minor = [0, 2, 3, 6, 7, 9, 10]
romanian-major = [0, 1, 4, 6, 7, 9, 10]
minor-romani = [0, 2, 3, 6, 7, 8, 10]
minor-romani-inverse = [0, 2, 4, 5, 6, 9, 10]
major-romani = [0, 1, 4, 5, 7, 8, 11]
spanish-romani = [0, 1, 4, 5, 7, 8, 10]
hungarian-romani = [0, 1, 3, 5, 7, 8, 11]
hungarian-romani-inverse = [0, 1, 4, 5, 7, 9, 11]
persian = [0, 1, 4, 5, 6, 8, 11]
asian = [0, 1, 4, 5, 6, 8, 10]

[8-tone]
mongolian = [0, 2, 4, 5, 6, 7, 9, 11]
chinese = [0, 2, 4, 5, 7, 9, 10, 11]
spanish = [0, 1, 3, 4, 5, 6, 8, 10]
spanish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10]
arabian-octotonic = [0, 2, 3, 5, 6, 8, 9, 11]
algerian = [0, 2, 3, 5, 6, 7, 8, 11]
jewish = [0, 1, 2, 3, 5, 7, 9, 10]

[9-tone]
moorish-phrygian = [0, 1, 3, 4, 5, 7, 8, 10, 11]
