[[modes]]
  ordinal = 1
  slug = "lyd-x2-x6"
  canonical = "Lydian ×2 ×6"
  degrees = "P1 Δ3 ♯4 P5 Δ7"
  tunings = [
    "F A B C E",
    "F A▷ B▷ C E▷",
  ]

  [modes.names]
    Ethiopian = "Bati [Batti] Lydian"
    Hindustani = "Raag Amritvarshini"
    Carnatic = "Amr̥tavarṣiṇi Rāgam"
    Japanese = "In (F mode)"

[[modes]]
  ordinal = 2
  slug = "ion-x2-x5"
  canonical = "Ionian ×2 ×5"
  degrees = "P1 Δ3 P4 Δ6 Δ7"
  tunings = [
    "C E F A B",
    "C E▷ F A▷ B▷",
  ]

  [modes.names]
    Hindustani = "Raag Bhinna Shadja"
    Japanese = "In (C mode)"

[[modes]]
  ordinal = 5
  slug = "aeo-x4-x7"
  canonical = "Aeolian ×4 ×7"
  degrees = "P1 Δ2 ♭3 P5 ♭6"
  tunings = [
    "A B C E F",
    "A▷ B▷ C E▷ F",
  ]

[[modes]]
  ordinal = 6
  slug = "phr-x3-x7"
  canonical = "Phrygian ×3 ×7"
  degrees = "P1 ♭2 P4 P5 ♭6"
  tunings = [
    "E F A B C",
    "E▷ F A▷ B▷ C",
  ]

  [modes.names]
    Ethiopian = "Ambassel"
    Hindustani = "Raag Gunakri"
    Carnatic = "Karnataka Śuddha Sāveri Rāgam, Asāvēri Rāgam (ascending)"
    Japanese = "Miyako-bushi, In (E mode)"

[[modes]]
  ordinal = 7
  slug = "loc-x3-x6"
  canonical = "Locrian ×3 ×6"
  degrees = "P1 ♭2 P4 ♯4 ♭7"

  tunings = [
    "B C E F A",
    "B▷ C E▷ F A▷",
  ]

  [modes.names]
    Ethiopian = "Anchihoye"
    Japanese = "In (B mode)"
