[[modes]]
  ordinal = 1
  slug = "lyd-x3-x6"
  canonical = "Lydian ×3 ×6"
  degrees = ""
  tunings = [
    "F G B C E",
    "F G B▷ C E▷",
  ]

  [modes.names]
    Carnatic = "Hamsanādam Rāgam"
    Japanese = "Ryu-kyu (F mode)"

[[modes]]
  ordinal = 2
  slug = "ion-x2-x6"
  canonical = "Ionian ×2 ×6"
  tunings = [
    "C E F G B",
    "C E▷ F G B▷",
  ]

  [modes.names]
    Ethiopian = "Bati [Batti] Major"
    Carnatic = "Gambhiranata Rāgam"
    Japanese = "Ryu-kyu (C mode)"

[[modes]]
  ordinal = 3
  slug = "mix-x2-x5"
  canonical = "Mixolydian ×2 ×5"
  tunings = [
    "G B C E F",
    "G B▷ C E▷ F",
  ]

  [modes.names]
    Japanese = "Ryu-kyu (G mode)"

[[modes]]
  ordinal = 6
  slug = "phr-x4-x7"
  canonical = "Phrygian ×4 ×7"
  tunings = [
    "E F G B C",
    "E▷ F G B▷ C",
  ]

  [modes.names]
    Hindustani = "Raag Bhoopal [Bhupal] Todi"
    Carnatic = "Bhūpalam Rāgam"
    Japanese = "Ryu-kyu (E mode)"

[[modes]]
  ordinal = 7
  slug = "loc-x3-x7"
  canonical = "Locrian ×3 ×7"
  tunings = [
    "B C E F G",
    "B▷ C E▷ F G",
  ]

  [modes.names]
    Japanese = "Ryu-kyu (B mode)"
