[[modes]]
  ordinal = 1
  slug = "lyd-x3-x7"
  canonical = "Lydian ×3 ×7"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = []
    4 = [1]
    5 = [1]
    6 = [1]
    7 = []

[[modes]]
  ordinal = 2
  slug = "ion-x3-x6"
  canonical = "Ionian ×3 ×6"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = []
    4 = [0]
    5 = [1]
    6 = []
    7 = [1]

[[modes]]
  ordinal = 3
  slug = "mix-x2-x6"
  canonical = "Mixolydian ×2 ×6"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [1]
    4 = [0]
    5 = [1]
    6 = []
    7 = [0]

[[modes]]
  ordinal = 4
  slug = "dor-x2-x5"
  canonical = "Dorian ×2 ×5"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [0]
    4 = [0]
    5 = []
    6 = [1]
    7 = [0]

  [modes.names]
    Hindustani = "Raag Chandrakauns (older form)"
