[[modes]]
  ordinal = 1
  slug = "lyd-ion-mix"
  canonical = "Lydian/Ionian/Mixolydian Pentatonic"
  degrees = "P1 Δ2 Δ3 P5 Δ6"

  [modes.tunings]
    symmetrical = "F G A C D"
    just-major = "G A B D E"
    just-minor = "E♭ F G B♭ C"
    septimal-major = "G A C♭ D F♭"
    tridecimal-major = "G A B▷ D E▷"
    unidecimal-major = "F G A▷ C D▷"

  [modes.names]
    Western = "Major Pentatonic"
    Ethiopian = "Tizita [Tezita] (major)"
    Hindustani = "Raag Bhoop [Bhoopali, Bhupālī]"
    Carnatic = "Mohanam Rāgam"
    Chinese = "Gong"
    Japanese = "Ryo, Yo (C mode)"

[[modes]]
  ordinal = 2
  slug = "ion-mix-dor"
  canonical = "Ionian/Mixolydian/Dorian Pentatonic"
  degrees = "P1 Δ2 P4 P5 Δ6"

  [modes.tunings]
    symmetrical = "C D F G A"
    major = "D E G A B"
    minor = "B♭ C E♭ F G"
    septimal = "D F♭ G A C♭"
    Zhi = "F G B♭ C D"


  [[modes.tunings]]
    intervals = "11/9 - 10/9 - 11/10"
    major = "P1[0] Δ2[-35] P4[+12] P5[-6] Δ6[-41]"
    names = ["Ho Mai Nhi"]

  [[modes.tunings]]
    intervals = "6/5 - 9/8 - 10/9"
    major = "P1[0] Δ2[-18] P4[-2] P5[+2] Δ6[-16]"
    minor = "P1[0] Δ2[-18] P4[-2] P5[-20] Δ6[-16]"
    names = ["Just", "Bac"]

  [[modes.tunings]]
    intervals = "6/5 - 9/8 - 10/9"
    major = "P1[0] Δ2[+4] P4[+21] P5[+2] Δ6[+6]"
    names = ["Zhi"]

  [modes.names]
    Western = "Scottish Pentatonic"
    Hindustani = "Raag Durga"
    Carnatic = "Śuddha Sāveri Rāgam"
    Chinese = "Zhi"
    Korean = "Pyeongjo [P’yŏngjo]"
    Japanese = "Ritsu, Yo (G mode)"
    Vietnamese = "Hoi Bac [Hơi Bắc], Ho Mai Nhi"

[[modes]]
  ordinal = 3
  slug = "mix-dor-aeo"
  canonical = "Mixolydian/Dorian/Aeolian Pentatonic"
  degrees = "P1 Δ2 P4 P5 ♭7"

  [modes.tunings]
    symmetrical = "G A C D F"
    major = "A B D E G"
    minor = "F G B♭ C E♭"
    septimal = "A C♭ D F♭ G"

  [[m]]
    name = "Harmonic 10/9 (minor), Shang"
    adjustments = "P1[0] Δ2[+4] P4[+20] P5[+2] ♭7[+18]"

  [[modes.tunings]]
    name = "Hơi Xuân"
    adjustments = "P1[0] Δ2[-35] P4[+1] P5[-17] ♭7[+35]"

  [modes.names]
    Ethiopian = "Yematebela Wof (popular song)"
    Hindustani = "Raag Madhumad Sarang"
    Carnatic = "Madhyamāvati Rāgam"
    Chinese = "Shang"
    Japanese = "Yo (D mode)"
    Vietnamese = "Hơi Xuân"

[[modes]]
  ordinal = 4
  slug = "dor-aeo-phr"
  canonical = "Dorian/Aeolian/Phrygian Pentatonic"
  degrees = "P1 ♭3 P4 P5 ♭7"

  [modes.tunings]
    symmetrical = "D F G A C"
    major = "E G A B D"
    minor = "C E♭ F G B♭"
    septimal = "F♭ G A C♭ D"

  [[modes.tunings]]
    name = "Yu"
    adjustments = "P1[0] ♭3[+26] P4[+21] P5[+2] ♭7[+19]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (minor), Sa Mac"
    adjustments = "P1[0] ♭3[+33] P4[-2] P5[+2] ♭7[+35]"


  [modes.names]
    Western = "Minor Pentatonic"
    Ethiopian = "Bati [Batti] (minor)"
    Hindustani = "Raag Dhani"
    Carnatic = "Udayaravichandrika Rāgam, Śuddha Dhanyasi Rāgam"
    Chinese = "Yu"
    Korean = "Gyemyeonjo [Kyemyŏnjo]"
    Japanese = "Min-yo [Min'yō], Yo (A mode)"
    Vietnamese = "Hơi Sa Mac"

[[modes]]
  ordinal = 5
  slug = "aeo-phr-loc"
  canonical = "Aeolian/Phrygian/Locrian Pentatonic"
  degrees = "P1 ♭3 P4 ♭6 ♭7"

  [modes.tunings]
    symmetrical = "A C D F G"
    major = "B D E G A"
    minor = "G B♭ C E♭ F"
    septimal = "C♭ D F♭ G A"


  [[modes.tunings]]
    name = "Harmonic 10/9 (major)"
    adjustments = "P1[0] ♭3[+16] P4[-2] ♭6[+14] ♭7[+18]"

  [[modes.tunings]]
    name = "Jue"
    adjustments = "P1[0] ♭3[+26] P4[+23] ♭6[+16] ♭7[+19]"


  [modes.names]
    Ethiopian = "Shegaye [Shegye Shegitu] (popular song)"
    Hindustani = "Raag Malkauns"
    Carnatic = "Hindōḷaṃ Rāgam"
    Chinese = "Jue"
    Japanese = "Yo (E mode)"
