[[modes]]
  ordinal = 1
  slug = "lyd-ion-mix"
  canonical = "Lydian/Ionian/Mixolydian Pentatonic"
  degrees = "P1 Δ2 Δ3 P5 Δ6"

  [[modes.tunings]]
    intervals = "11/9 - 9/8 - 12/11"
    major = "P1[0] Δ2[+4] Δ3[-45] P5[+2] Δ6[-47]"
    minor = "P1[0] Δ2[-49] Δ3[-45] P5[+2] Δ6[-47]"

  [[modes.tunings]]
    intervals = "40/33 - 9/8 - 11/10"
    major = "P1[0] Δ2[+4] Δ3[-31] P5[+2] Δ6[-33]"
    minor = "P1[0] Δ2[-35] Δ3[-31] P5[+2] Δ6[-33]"

  [[modes.tunings]]
    intervals = "76/63 - 9/8 - 21/19"
    major = "P1[0] Δ2[+4] Δ3[-23] P5[+2] Δ6[-25]"
    minor = "P1[0] Δ2[-27] Δ3[-23] P5[+2] Δ6[-25]"

  [[modes.tunings]]
    intervals = "6/5 - 9/8 - 10/9"
    major = "P1[0] Δ2[+4] Δ3[-14] P5[+2] Δ6[-16]"
    minor = "P1[0] Δ2[-18] Δ3[-14] P5[+2] Δ6[-16]"
    names = ["Just"]

  [[modes.tunings]]
    intervals = "68/57 - 9/8 - 19/17"
    major = "P1[0] Δ2[+4] Δ3[-3] P5[+2] Δ6[-5]"
    minor = "P1[0] Δ2[-7] Δ3[-3] P5[+2] Δ6[-5]"

  [[modes.tunings]]
    intervals = "32/27 - 9/8"
    major = "P1[0] Δ2[+4] Δ3[+8] P5[+2] Δ6[+6]"
    minor = "P1[0] Δ2[+4] Δ3[+8] P5[+2] Δ6[+6]"
    names = ["Pythagorean", "Gong"]

  [[modes.tunings]]
    intervals = "20/17 - 17/15 - 9/8"
    major = "P1[0] Δ2[+4] Δ3[+21] P5[+2] Δ6[+19]"
    minor = "P1[0] Δ2[+17] Δ3[+21] P5[+2] Δ6[+19]"

  [[modes.tunings]]
    intervals = "7/6 - 8/7 - 9/8"
    major = "P1[0] Δ2[+4] Δ3[+35] P5[+2] Δ6[+33]"
    minor = "P1[0] Δ2[+31] Δ3[+35] P5[+2] Δ6[+33]"

  [[modes.tunings]]
    intervals = "52/45 - 15/13 - 9/8"
    major = "P1[0] Δ2[+4] Δ3[+52] P5[+2] Δ6[+50]"
    minor = "P1[0] Δ2[+48] Δ3[+52] P5[+2] Δ6[+50]"

  [modes.names]
    Western = "Major Pentatonic"
    Ethiopian = "Tizita [Tezita] (major)"
    Hindustani = "Raag Bhoop [Bhoopali, Bhupālī]"
    Carnatic = "Mohanam Rāgam"
    Chinese = "Gong"
    Japanese = "Ryo, Yo (C mode)"

[[modes]]
  ordinal = 2
  slug = "ion-mix-dor"
  canonical = "Ionian/Mixolydian/Dorian Pentatonic"
  degrees = "P1 Δ2 P4 P5 Δ6"

  [[modes.tunings]]
    intervals = "11/9 - 9/8 - 12/11"
    major = "P1[0] Δ2[-49] P4[-2] P5[+2] Δ6[-47]"
    minor = "P1[0] Δ2[-49] P4[-2] P5[-51] Δ6[-47]"

  [[modes.tunings]]
    intervals = "40/33 - 9/8 - 11/10"
    major = "P1[0] Δ2[-35] P4[-2] P5[+2] Δ6[-33]"
    minor = "P1[0] Δ2[-35] P4[-2] P5[-37] Δ6[-33]"

  [[modes.tunings]]
    intervals = "6/5 - 9/8 - 10/9"
    major = "P1[0] Δ2[-18] P4[-2] P5[+2] Δ6[-16]"
    minor = "P1[0] Δ2[-18] P4[-2] P5[-20] Δ6[-16]"
    names = ["Just", "Bac"]

  [[modes.tunings]]
    intervals = "32/27 - 9/8"
    major = "P1[0] Δ2[+4] P4[-2] P5[+2] Δ6[+6]"
    minor = "P1[0] Δ2[+4] P4[-2] P5[+2] Δ6[+6]"
    names = ["Pythagorean"]

  [[modes.tunings]]
    intervals = "6/5 - 32/27 - 9/8 - 10/9"
    major = "P1[0] Δ2[+4] P4[+21] P5[+2] Δ6[+6]"
    names = ["Zhi"]

  [[modes.tunings]]
    name = "Ho Mai Nhi"
    adjustments = "P1[0] Δ2[-35] P4[+20] P5[+2] Δ6[-33]"

  [[modes.tunings]]
    name = "Harmonic 17/15"
    adjustments = "P1[0] Δ2[+17] P4[-2] P5[+2] Δ6[+19]"

  [[modes.tunings]]
    name = "Harmonic 8/7"
    adjustments = "P1[0] Δ2[+31] P4[-2] P5[+2] Δ6[+33]"

  [[modes.tunings]]
    name = "Harmonic 15/13"
    adjustments = "P1[0] Δ2[+48] P4[-2] P5[+2] Δ6[+50]"

  [modes.names]
    Western = "Scottish Pentatonic"
    Hindustani = "Raag Durga"
    Carnatic = "Śuddha Sāveri Rāgam"
    Chinese = "Zhi"
    Korean = "Pyeongjo [P’yŏngjo]"
    Japanese = "Ritsu, Yo (G mode)"
    Vietnamese = "Hoi Bac [Hơi Bắc], Ho Mai Nhi"

[[modes]]
  ordinal = 3
  slug = "mix-dor-aeo"
  canonical = "Mixolydian/Dorian/Aeolian Pentatonic"
  degrees = "P1 Δ2 P4 P5 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] P4[-2] P5[+2] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 10/9 (minor), Shang"
    adjustments = "P1[0] Δ2[+4] P4[+20] P5[+2] ♭7[+18]"

  [[modes.tunings]]
    name = "Harmonic 10/9 (major)"
    adjustments = "P1[0] Δ2[-18] P4[-2] P5[-20] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (minor)"
    adjustments = "P1[0] Δ2[+4] P4[+37] P5[+2] ♭7[+35]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (major)"
    adjustments = "P1[0] Δ2[-35] P4[-2] P5[-37] ♭7[-4]"

  [[modes.tunings]]
    name = "Hơi Xuân"
    adjustments = "P1[0] Δ2[-35] P4[-2] P5[+2] ♭7[+35]"

  [[modes.tunings]]
    name = "Harmonic 12/11 (minor)"
    adjustments = "P1[0] Δ2[+4] P4[+51] P5[+2] ♭7[+49]"

  [[modes.tunings]]
    name = "Harmonic 12/11 (major)"
    adjustments = "P1[0] Δ2[-49] P4[-2] P5[-51] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 17/15"
    adjustments = "P1[0] Δ2[+17] P4[-2] P5[+15] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 8/7"
    adjustments = "P1[0] Δ2[+31] P4[-2] P5[+29] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 15/13"
    adjustments = "P1[0] Δ2[+48] P4[-2] P5[+46] ♭7[-4]"

  [modes.names]
    Ethiopian = "Yematebela Wof (popular song)"
    Hindustani = "Raag Madhumad Sarang"
    Carnatic = "Madhyamāvati Rāgam"
    Chinese = "Shang"
    Japanese = "Yo (D mode)"
    Vietnamese = "Hơi Xuân"

[[modes]]
  ordinal = 4
  slug = "dor-aeo-phr"
  canonical = "Dorian/Aeolian/Phrygian Pentatonic"
  degrees = "P1 ♭3 P4 P5 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] ♭3[-6] P4[-2] P5[+2] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 10/9 (minor)"
    adjustments = "P1[0] ♭3[+16] P4[-2] P5[+2] ♭7[+18]"

  [[modes.tunings]]
    name = "Harmonic 10/9 (major)"
    adjustments = "P1[0] ♭3[+16] P4[+20] P5[+2] ♭7[+18]"

  [[modes.tunings]]
    name = "Yu"
    adjustments = "P1[0] ♭3[+26] P4[+21] P5[+2] ♭7[+19]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (minor), Sa Mac"
    adjustments = "P1[0] ♭3[+33] P4[-2] P5[+2] ♭7[+35]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (major)"
    adjustments = "P1[0] ♭3[+33] P4[+37] P5[+2] ♭7[+35]"

  [[modes.tunings]]
    name = "Harmonic 12/11 (minor)"
    adjustments = "P1[0] ♭3[+47] P4[-2] P5[+2] ♭7[+49]"

  [[modes.tunings]]
    name = "Harmonic 12/11 (major)"
    adjustments = "P1[0] ♭3[+47] P4[+51] P5[+2] ♭7[+49]"

  [[modes.tunings]]
    name = "Harmonic 20/17"
    adjustments = "P1[0] ♭3[-19] P4[-15] P5[+2] ♭7[-17]"

  [[modes.tunings]]
    name = "Harmonic 7/6"
    adjustments = "P1[0] ♭3[-33] P4[-29] P5[+2] ♭7[-31]"

  [[modes.tunings]]
    name = "Harmonic 37/32"
    adjustments = "P1[0] ♭3[-49] P4[-45] P5[+2] ♭7[-47]"

  [modes.names]
    Western = "Minor Pentatonic"
    Ethiopian = "Bati [Batti] (minor)"
    Hindustani = "Raag Dhani"
    Carnatic = "Udayaravichandrika Rāgam, Śuddha Dhanyasi Rāgam"
    Chinese = "Yu"
    Korean = "Gyemyeonjo [Kyemyŏnjo]"
    Japanese = "Min-yo [Min'yō], Yo (A mode)"
    Vietnamese = "Hơi Sa Mac"

[[modes]]
  ordinal = 5
  slug = "aeo-phr-loc"
  canonical = "Aeolian/Phrygian/Locrian Pentatonic"
  degrees = "P1 ♭3 P4 ♭6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] ♭3[-6] P4[-2] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 10/9 (minor)"
    adjustments = "P1[0] ♭3[+16] P4[-2] ♭6[+14] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (minor)"
    adjustments = "P1[0] ♭3[+33] P4[-2] ♭6[+31] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 12/11 (minor)"
    adjustments = "P1[0] ♭3[+47] P4[-2] ♭6[+45] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 10/9 (major)"
    adjustments = "P1[0] ♭3[+16] P4[-2] ♭6[+14] ♭7[+18]"

  [[modes.tunings]]
    name = "Jue"
    adjustments = "P1[0] ♭3[+26] P4[+23] ♭6[+16] ♭7[+19]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (major)"
    adjustments = "P1[0] ♭3[+33] P4[-2] P5[+31] ♭7[+35]"

  [[modes.tunings]]
    name = "Harmonic 12/11 (major)"
    adjustments = "P1[0] ♭3[+47] P4[-2] ♭6[+45] ♭7[+49]"

  [modes.names]
    Ethiopian = "Shegaye [Shegye Shegitu] (popular song)"
    Hindustani = "Raag Malkauns"
    Carnatic = "Hindōḷaṃ Rāgam"
    Chinese = "Jue"
    Japanese = "Yo (E mode)"
