[[modes]]
  ordinal = 1
  slug = "lyd-ion-mix"
  canonical = "Lydian/Ionian/Mixolydian Pentatonic"
  degrees = "P1 Δ2 Δ3 P5 Δ6"

  [modes.tunings]
    Pythagorean = "F G A C D"
    just-major = "G A B D E"
    just-minor = "E♭ F G B♭ C"
    wolf-major = "B♭ C D F G"
    wolf-minor = "D♭ E♭ F A♭ B♭"

  [modes.names]
    Western = "Major Pentatonic"
    Ethiopian = "Tizita [Tezita] (major)"
    Hindustani = "Raag Bhoop [Bhoopali, Bhupālī]"
    Carnatic = "Mohanam Rāgam"
    Chinese = "Gong"
    Japanese = "Ryo, Yo (C mode)"

[[modes]]
  ordinal = 2
  slug = "ion-mix-dor"
  canonical = "Ionian/Mixolydian/Dorian Pentatonic"
  degrees = "P1 Δ2 P4 P5 Δ6"

  [modes.tunings]
    Pythagorean = "C D F G A"
    just-major = "D E G A B"
    just-minor = "B♭ C E♭ F G"
    wolf-major = "F G B♭ C D"
    wolf-minor = "A♭ B♭ D♭ E♭ F"

  [modes.names]
    Western = "Scottish Pentatonic"
    Hindustani = "Raag Durga"
    Carnatic = "Śuddha Sāveri Rāgam"
    Chinese = "Zhi"
    Korean = "Pyeongjo [P’yŏngjo]"
    Japanese = "Ritsu, Yo (G mode)"
    Vietnamese = "Hơi Bắc"

[[modes]]
  ordinal = 3
  slug = "mix-dor-aeo"
  canonical = "Mixolydian/Dorian/Aeolian Pentatonic"
  degrees = "P1 Δ2 P4 P5 ♭7"

  [modes.tunings]
    Pythagorean = "G A C D F"
    just-major = "A B D E G"
    just-minor = "F G B♭ C E♭"
    wolf-major = "C D F G B♭"
    wolf-minor = "E♭ F A♭ B♭ D♭"

  [modes.names]
    Ethiopian = "Yematebela Wof (popular song)"
    Hindustani = "Raag Madhumad Sarang"
    Carnatic = "Madhyamāvati Rāgam"
    Chinese = "Shang"
    Japanese = "Yo (D mode)"

[[modes]]
  ordinal = 4
  slug = "dor-aeo-phr"
  canonical = "Dorian/Aeolian/Phrygian Pentatonic"
  degrees = "P1 ♭3 P4 P5 ♭7"

  [modes.tunings]
    Pythagorean = "D F G A C"
    just-major = "E G A B D"
    just-minor = "C E♭ F G B♭"
    wolf-major = "G B♭ C D F"
    wolf-minor = "B♭ D♭ E♭ F A♭"

  [modes.names]
    Western = "Minor Pentatonic"
    Ethiopian = "Bati [Batti] (minor)"
    Hindustani = "Raag Dhani"
    Carnatic = "Udayaravichandrika Rāgam, Śuddha Dhanyasi Rāgam"
    Chinese = "Yu"
    Korean = "Gyemyeonjo [Kyemyŏnjo]"
    Japanese = "Min-yo [Min'yō], Yo (A mode)"
    Vietnamese = "Hơi Sa Mac"

[[modes]]
  ordinal = 5
  slug = "aeo-phr-loc"
  canonical = "Aeolian/Phrygian/Locrian Pentatonic"
  degrees = "P1 ♭3 P4 ♭6 ♭7"

  [modes.tunings]
    Pythagorean = "A C D F G"
    just-major = "B D E G A"
    just-minor = "G B♭ C E♭ F"
    wolf-major = "D F G B♭ C"
    wolf-minor = "F A♭ B♭ D♭ E♭"

  [modes.names]
    Ethiopian = "Shegaye [Shegye Shegitu] (popular song)"
    Hindustani = "Raag Malkauns"
    Carnatic = "Hindōḷaṃ Rāgam"
    Chinese = "Jue"
    Japanese = "Yo (E mode)"
