[[modes]]
  ordinal = 1
  slug = "lyd-r2-b7"
  canonical = "Lydian ↑2 ♭7"
  degrees = "P1 ♭3 Δ3 ♯4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "G♭ A B♭ C D♭ E♭ F♭"
    minor = "A♭ B C D E♭ F G♭"

  [modes.names]

[[modes]]
  ordinal = 2
  slug = "ion-b3-r5"
  canonical = "Ionian ♭3 ↑5"
  degrees = "P1 Δ2 ♭3 P4 ♭6 Δ6 Δ7"

  [modes.tunings]
    major = "D♭ E♭ F♭ G♭ A B♭ C"
    minor = "E♭ F G♭ A♭ B C D"

  [modes.names]

[[modes]]
  ordinal = 4
  slug = "dor-b2-s4"
  canonical = "Dorian ♭2 ♯4"
  degrees = "P1 ♭2 ♭3 ♯4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "E♭ F♭ G♭ A B♭ C D♭"
    minor = "F G♭ A♭ B C D E♭"

  [modes.names]

[[modes]]
  ordinal = 5
  slug = "aeo-l5-maj7"
  canonical = "Aeolian ↓5 Δ7"
  degrees = "P1 Δ2 ♭3 P4 ♯4 ♭6 Δ7"

  [modes.tunings]
    major = "B♭ C D♭ E♭ F♭ G♭ A"
    minor = "C D E♭ F G♭ A♭ B"

  [modes.names]

[[modes]]
  ordinal = 7
  slug = "loc-l4-maj6"
  canonical = "Locrian ↓4 Δ6"
  degrees = "P1 ♭2 ♭3 Δ3 ♯4 Δ6 ♭7"

  [modes.tunings]
    major = "C D♭ E♭ F♭ G♭ A B♭"
    minor = "D E♭ F G♭ A♭ B C"

[[modes]]
  ordinal = 10
  slug = "loc-l4-l6-l7"
  canonical = "Locrian ↓4 ↓6 ↓7"
  degrees = "P1 ♭2 ♭3 Δ3 ♯4 P5 Δ6"

  [modes.tunings]
    major = "A B♭ C D♭ E♭ F♭ G♭"
    minor = "B C D E♭ F G♭ A♭"

[[modes]]
  ordinal = 11
  slug = "lyd-r3-r5"
  canonical = "Lydian ↑3 ↑5"
  degrees = "P1 Δ2 P4 ♯4 ♭6 Δ6 Δ7"

  [modes.tunings]
    major = "E♭ F♭ G♭ A B♭ C D♭"
    minor = "F G♭ A♭ B C D E♭"
