[[modes]]
  ordinal = 1
  slug = "lyd-r2"
  canonical = "Lydian ↑2"
  degrees = "P1 ♭3 Δ3 ♯4 P5 Δ6 Δ7"
  tunings = [
    "A♭ B C D E♭ F G",
    "B♭ C♯ D E F G A",
  ]

  [modes.names]
    Carnatic = "Kōsalam (71st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 2
  slug = "ion-r5"
  canonical = "Ionian ↑5"
  degrees = "P1 Δ2 Δ3 P4 ♭6 Δ6 Δ7"
  tunings = [
    "E♭ F G A♭ B C D",
    "F G A B♭ C♯ D E",
  ]

[[modes]]
  ordinal = 4
  slug = "dor-s4"
  canonical = "Dorian ♯4"
  degrees = "P1 Δ2 ♭3 ♯4 P5 Δ6 ♭7"
  tunings = [
    "F G A♭ B C D E♭",
    "G A B♭ C♯ D E F",
  ]

  [modes.names]
    Western = "Ukrainian Dorian, Romanian Minor"
    Ashkenazi = "Misheberekh Mode"
    Arabic = "Maqam Nikriz"
    Carnatic = "Hēmavati (58th Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 5
  slug = "aeo-maj7"
  canonical = "Aeolian Δ7"
  degrees = "P1 Δ2 ♭3 P4 P5 ♭6 Δ7"
  tunings = [
    "C D E♭ F G A♭ B",
    "D E F G A B♭ C♯",
  ]

  [modes.names]
    Western = "Harmonic Minor"
    Arabic = "Maqam Nahawand-Hijaz"
    Turkish = "Bûselik-Hicaz Makam"
    Carnatic = "Keeravāṇi (21st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 6
  slug = "phr-maj3"
  canonical = "Phrygian Δ3"
  degrees = "P1 ♭2 Δ3 P4 P5 ♭6 ♭7"
  tunings = [
    "G A♭ B C D E♭ F",
    "A B♭ C♯ D E F G",
  ]

  [modes.names]
    Western = "Phrygian Dominant, Spanish Phrygian"
    Ashkenazi = "Ahava Rabbah Mode, Freygish"
    Iberian = "Escala Andaluza"
    Arabic = "Maqam Hijaz-Nahawand"
    Carnatic = "Vakuḷābharaṇam (14th Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 7
  slug = "loc-maj6"
  canonical = "Locrian Δ6"
  degrees = "P1 ♭2 ♭3 P4 ♯4 Δ6 ♭7"
  tunings = [
    "D E♭ F G A♭ B C",
    "E F G A B♭ C♯ D",
  ]
