[[modes]]
  ordinal = 1
  slug = "lyd-r2"
  canonical = "Lydian ↑2"
  degrees = "P1 ♭3 Δ3 ♯4 P5 Δ6 Δ7"

  [modes.tunings]
    major = "G♭ A B♭ C D♭ E♭ F"
    minor = "A♭ B C D E♭ F G"

  [modes.names]
    Carnatic = "Kōsalam (71st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 2
  slug = "ion-r5"
  canonical = "Ionian ↑5"
  degrees = "P1 Δ2 Δ3 P4 ♭6 Δ6 Δ7"

  [modes.tunings]
    major = "D♭ E♭ F G♭ A B♭ C"
    minor = "E♭ F G A♭ B C D"

  [modes.names]

[[modes]]
  ordinal = 4
  slug = "dor-s4"
  canonical = "Dorian ♯4"
  degrees = "P1 Δ2 ♭3 ♯4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "E♭ F G♭ A B♭ C D♭"
    minor = "F G A♭ B C D E♭"

  [modes.names]
    Western = "Ukrainian Dorian, Romanian Minor"
    Ashkenazi = "Misheberekh Mode"
    Arabic = "Maqam Nikriz"
    Carnatic = "Hēmavati (58th Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 5
  slug = "aeo-maj7"
  canonical = "Aeolian Δ7"
  degrees = "P1 Δ2 ♭3 P4 P5 ♭6 Δ7"

  [modes.tunings]
    major = "B♭ C D♭ E♭ F G♭ A"
    minor = "C D E♭ F G A♭ B"

  [modes.names]
    Western = "Harmonic Minor"
    Arabic = "Maqam Nahawand-Hijaz"
    Turkish = "Bûselik-Hicaz Makam"
    Carnatic = "Keeravāṇi (21st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 6
  slug = "phr-maj3"
  canonical = "Phrygian Δ3"
  degrees = "P1 ♭2 Δ3 P4 P5 ♭6 ♭7"

  [modes.tunings]
    major = "F G♭ A B♭ C D♭ E♭"
    minor = "G A♭ B C D E♭ F"

  [modes.names]
    Western = "Phrygian Dominant, Spanish Phrygian"
    Ashkenazi = "Ahava Rabbah Mode, Freygish"
    Iberian = "Escala Andaluza"
    Arabic = "Maqam Hijaz-Nahawand"
    Carnatic = "Vakuḷābharaṇam (14th Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 7
  slug = "loc-maj6"
  canonical = "Locrian Δ6"
  degrees = "P1 ♭2 ♭3 P4 ♯4 Δ6 ♭7"

  [modes.tunings]
    major = "C D♭ E♭ F G♭ A B♭"
    minor = "D E♭ F G A♭ B C"

  [modes.names]

[[modes]]
  ordinal = 10
  slug = "loc-l4-l7"
  canonical = "Locrian ↓4 ↓7"
  degrees = "P1 ♭2 ♭3 Δ3 ♯4 ♭6 Δ6"

  [modes.tunings]
    major = "A B♭ C D♭ E♭ F G♭"
    minor = "B C D E♭ F G A♭"

    [modes.names]
