[[modes]]
  ordinal = 1
  slug = "lyd-r2"
  canonical = "Lydian ↑2"
  degrees = "P1 ‖2 Δ3 ♯4 P5 Δ6 Δ7"

  [modes.tunings]
    minor = "A♭ ▷B C D E♭ F G"
    septimal = "C♭ D E♭ F G♭ A♭ B♭"

  [modes.names]
    Carnatic = "Kōsalam (71st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 2
  slug = "ion-r5"
  canonical = "Ionian ↑5"
  degrees = "P1 Δ2 Δ3 P4 ♭6 Δ6 Δ7"

  [modes.tunings]
    minor = "E♭ F G A♭ B C D"
    septimal = "G♭ A♭ B♭ C♭ D E♭ F"

  [modes.names]

[[modes]]
  ordinal = 4
  slug = "dor-s4"
  canonical = "Dorian ♯4"
  degrees = "P1 Δ2 ♭3 ♯4 P5 Δ6 ♭7"

  [modes.tunings]
    minor = "F G A♭ B C D E♭"
    septimal = "A♭ B♭ C♭ D E♭ F G♭"

  [modes.names]
    Western = "Ukrainian Dorian, Romanian Minor"
    Ashkenazi = "Misheberekh Mode"
    Arabic = "Maqam Nikriz"
    Carnatic = "Hēmavati (58th Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 5
  slug = "aeo-maj7"
  canonical = "Aeolian Δ7"
  degrees = "P1 Δ2 ♭3 P4 P5 ♭6 Δ7"

  [modes.tunings]
    minor = "C D E♭ F G A♭ B"
    septimal = "E♭ F G♭ A♭ B♭ C♭ D"

  [modes.names]
    Western = "Harmonic Minor"
    Arabic = "Maqam Nahawand-Hijaz"
    Turkish = "Bûselik-Hicaz Makam"
    Carnatic = "Keeravāṇi (21st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 6
  slug = "bayati-rast-maj3"
  canonical = "Bayati-Rast Δ3"
  degrees = "P1 ▷2 Δ3 P4 P5 ▷6 ♭7"

  [modes.tunings]
    major = "E F‖ G♯ A B C‖ D"
    minor = "G A▷ B C D E▷ F"

  [modes.names]

[[modes]]
  ordinal = 7
  slug = "loc-maj6"
  canonical = "Locrian Δ6"
  degrees = "P1 ♭2 ♭3 P4 ♯4 Δ6 ♭7"

  [modes.tunings]
    minor = "D E♭ F G A♭ B C"
    septimal = "F G♭ A♭ B♭ C♭ D E♭"

  [modes.names]

[[modes]]
  ordinal = 10
  slug = "loc-l4-l7"
  canonical = "Locrian ↓4 ↓7"
  degrees = "P1 ♭2 ♭3 Δ3 ♯4 ♭6 Δ6"

  [modes.tunings]
    minor = "B C D E♭ F G A♭"
    septimal = "D E♭ F G♭ A♭ B♭ C♭"

    [modes.names]
