[[modes]]
  ordinal = 1
  slug = "lyd-b3"
  canonical = "Lydian ♭3"
  degrees = "P1 Δ2 ♭3 ♯4 P5 Δ6 Δ7"

  [modes.tunings]
    major = "F G A♭ B C D E"
    minor = "D E F G♯ A B C♯"

  [modes.names]

[[modes]]
  ordinal = 2
  slug = "ion-b6"
  canonical = "Ionian ♭6"
  degrees = "P1 Δ2 Δ3 P4 P5 ♭6 Δ7"

  [modes.tunings]
    major = "C D E F G A♭ B"
    minor = "A B C♯ D E F G♯"

  [modes.names]
    Western = "Harmonic Major"

[[modes]]
  ordinal = 3
  slug = "mix-b2"
  canonical = "Mixolydian ♭2"
  degrees = "P1 ♭2 Δ3 P4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "G A♭ B C D E F"
    minor = "E F G♯ A B C♯ D"

  [modes.names]

[[modes]]
  ordinal = 4
  slug = "dor-l5"
  canonical = "Dorian ↓5"
  degrees = "P1 Δ2 ♭3 P4 ♯4 Δ6 ♭7"

  [modes.tunings]
    major = "D E F G A♭ B C"
    minor = "B C♯ D E F G♯ A"

  [modes.names]

[[modes]]
  ordinal = 6
  slug = "phr-l4"
  canonical = "Phrygian ↓4"
  degrees = "P1 ♭2 ♭3 Δ3 P5 ♭6 ♭7"

  [modes.tunings]
    major = "E F G A♭ B C D"
    minor = "C♯ D E F G♯ A B"

  [modes.names]

[[modes]]
  ordinal = 7
  slug = "loc-l7"
  canonical = "Locrian ↓7"
  degrees = "P1 ♭2 ♭3 P4 ♯4 ♭6 Δ6"

  [modes.tunings]
    major = "B C D E F G A♭"
    minor = "G♯ A B C♯ D E F"

  [modes.names]

[[modes]]
  ordinal = 10
  slug = "lyd-r2-r5"
  canonical = "Lydian ↑2 ↑5"
  degrees = "P1 ♭3 Δ3 P4 ♭6 Δ6 Δ7"

  [modes.tunings]
    major = "A♭ B C D E F G"
    minor = "F G♯ A B C♯ D E"

  [modes.names]
