[[modes]]
  ordinal = 1
  slug = "lyd-b7"
  canonical = "Lydian ♭7"
  degrees = "P1 Δ2 Δ3 ♯4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "F G A B C D E♭"
    minor = "A♭ B♭ C D E♭ F G♭"
    septimal = "D♭ E♭ F G A♭ B♭ C♭"

  [modes.names]

[[modes]]
  ordinal = 2
  slug = "ion-b3"
  canonical = "Ionian ♭3"
  degrees = "P1 Δ2 ♭3 P4 P5 Δ6 Δ7"

  [modes.tunings]
    major = "C D E♭ F G A B"
    minor = "E♭ F G♭ A♭ B♭ C D"
    septimal = "A♭ B♭ C♭ D♭ E♭ F G"

  [modes.names]

[[modes]]
  ordinal = 3
  slug = "mix-b6"
  canonical = "Mixolydian ♭6"
  degrees = "P1 Δ2 Δ3 P4 P5 ♭6 ♭7"

  [modes.tunings]
    major = "G A B C D E♭ F"
    minor = "B♭ C D E♭ F G♭ A♭"
    septimal = "E♭ F G A♭ B♭ C♭ D♭"

  [modes.names]

[[modes]]
  ordinal = 4
  slug = "dor-b2"
  canonical = "Dorian ♭2"
  degrees = "P1 ♭2 ♭3 P4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "D E♭ F G A B C"
    minor = "F G♭ A♭ B♭ C D E♭"
    septimal = "B♭ C♭ D♭ E♭ F G A♭"

  [modes.names]

[[modes]]
  ordinal = 5
  slug = "aeo-l5"
  canonical = "Aeolian ↓5"
  degrees = "P1 Δ2 ♭3 P4 ♯4 ♭6 ♭7"

  [modes.tunings]
    major = "A B C D E♭ F G"
    minor = "C D E♭ F G♭ A♭ B♭"
    septimal = "F G A♭ B♭ C♭ D♭ E♭"

  [modes.names]

[[modes]]
  ordinal = 7
  slug = "loc-l4"
  canonical = "Locrian ↓4"
  degrees = "P1 ♭2 ♭3 Δ3 ♯4 ♭6 ♭7"

  [modes.tunings]
    major = "B C D E♭ F G A"
    minor = "D E♭ F G♭ A♭ B♭ C"
    septimal = "G A♭ B♭ C♭ D♭ E♭ F"

  [modes.names]

[[modes]]
  ordinal = 11
  slug = "lyd-r5"
  canonical = "Lydian ↑5"
  degrees = "P1 Δ2 Δ3 ♯4 ♭6 Δ6 Δ7"

  [modes.tunings]
    major = "E♭ F G A B C D"
    minor = "G♭ A♭ B♭ C D E♭ F"
    septimal = "C♭ D♭ E♭ F G A♭ B♭"

  [modes.names]
