[[modes]]
  ordinal = 1
  slug = "lyd-b7"
  canonical = "Lydian ♭7"
  degrees = "P1 Δ2 Δ3 ♯4 P5 Δ6 ♭7"
  tunings = [
    "F G A B C D E♭",
    "A♭ B♭ C D E♭ F F♯",
  ]

  [modes.names]

[[modes]]
  ordinal = 2
  slug = "ion-b3"
  canonical = "Ionian ♭3"
  degrees = "P1 Δ2 ♭3 P4 P5 Δ6 Δ7"
  tunings = [
    "C D E♭ F G A B",
    "E♭ F F♯ A♭ B♭ C D",
  ]

  [modes.names]

[[modes]]
  ordinal = 3
  slug = "mix-b6"
  canonical = "Mixolydian ♭6"
  degrees = "P1 Δ2 Δ3 P4 P5 ♭6 ♭7"
  tunings = [
    "G A B C D E♭ F",
    "B♭ C D E♭ F F♯ A♭",
  ]

  [modes.names]