[[modes]]
  ordinal = 1
  slug = "lyd"
  canonical = "Lydian Mode"
  degrees = "P1 Δ2 Δ3 ♯4 P5 Δ6 Δ7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] ♯4[+12] P5[+2] Δ6[+6] Δ7[+10]"

  [[modes.tunings]]
    name = "Harmonic 10/9"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] ♯4[-10] P5[+2] Δ6[+6] Δ7[-12]"

  [[modes.tunings]]
    name = "Harmonic 11/10"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] ♯4[-27] P5[+2] Δ6[+6] Δ7[-29]"

  [[modes.tunings]]
    name = "Harmonic 12/11"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] ♯4[-41] P5[+2] Δ6[+6] Δ7[-43]"

  [[modes.tunings]]
    intervals = "19/17 - 102/95"
    tetrachord = "19/17 - 5/4 - 51/38"

  [modes.names]
    Hindustani = "Kalyan Thaat"
    Carnatic = "Kaḷyāṇi (65th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. #4/7)"

[[modes]]
  ordinal = 2
  slug = "ion"
  canonical = "Ionian Mode"
  degrees = "P1 Δ2 Δ3 P4 P5 Δ6 Δ7"

  [[modes.tunings]]
    intervals = "9/8, 256/243"
    tetrachords = "9/8 - 81/64 - 4/3 | 9/8 - 81/64 - 4/3"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] P4[-2] P5[+2] Δ6[+6] Δ7[+10]"
    names = "Pythagorean"

  [[modes.tunings]]
    intervals = "9/8, 10/9, 16/15"
    tetrachords = "9/8 - 5/4 - 4/3 | 9/8 - 5/4 - 4/3"
    adjustments = "P1[0] Δ2[+4] Δ3[-14] P4[-2] P5[+2] Δ6[+6] Δ7[-12]"
    names = "Just major"

  [[modes.tunings]]
    intervals = "19/17, 936/875"
    tetrachords = "19/17 - 5/4 - 234/175 | 19/17 - 5/4 - 234/175"
    adjustments = "P1[0] Δ2[-7] Δ3[-14] P4[+3] P5[-3] Δ6[-10] Δ7[-17]"
    names = "Quarter-comma meantone (rationalized)"

  [[modes.tunings]]
    intervals = "19/17, 29/27"
    tetrachords = "19/17 - 5/4 - 145/108 | 19/17 - 5/4 - 145/108"
    adjustments = "P1[0] Δ2[-7] Δ3[-14] P4[+9] P5[+2] Δ6[-5] Δ7[-12]"
    names = "Perfect-fifth/stretched-octave meantone (rationalized)"



  [[modes.tunings]]
    name = "Harmonic 11/10, Arabic Rast"
    adjustments = "P1[0] Δ2[+4] Δ3[-31] P4[-2] P5[+2] Δ6[+6] Δ7[-29]"

  [[modes.tunings]]
    name = "Harmonic 12/11, Arabic Rast"
    adjustments = "P1[0] Δ2[+4] Δ3[-45] P4[-2] P5[+2] Δ6[+6] Δ7[-43]"

  [modes.names]
    Western = "Major Scale"
    Arabic = "Maqam ‘Ajam (major 3/7), Maqam Rast (half-flat 3/7)"
    Turkish = "Acem/Çârgâh Makam (major 3/7), Rast Makam (quarter-flat 3/7)"
    Persian = "Dastgāh-e Māhur (lower octave)"
    Hindustani = "Bilaval [Bilawal] Thaat"
    Carnatic = "Śankarābharaṇaṃ [Dhīraśankarābharaṇaṃ] (29th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/7)"

[[modes]]
  ordinal = 3
  slug = "mix"
  canonical = "Mixolydian Mode"
  degrees = "P1 Δ2 Δ3 P4 P5 Δ6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] P4[-2] P5[+2] Δ6[+6] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 10/9, Turkish Rast (descending)"
    adjustments = "P1[0] Δ2[+4] Δ3[-14] P4[-2] P5[+2] Δ6[-16] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 11/10"
    adjustments = "P1[0] Δ2[+4] Δ3[-31] P4[-2] P5[+2] Δ6[-33] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 12/11"
    adjustments = "P1[0] Δ2[+4] Δ3[-45] P4[-2] P5[+2] Δ6[-47] ♭7[-4]"

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (lower octave)"
    Turkish = "Rast Makam (descending)"
    Persian = "Dastgāh-e Māhur (upper octave)"
    Hindustani = "Khamaj Thaat"
    Carnatic = "Harikāmbhōji (28th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/♭7)"

[[modes]]
  ordinal = 4
  slug = "dor"
  canonical = "Dorian Mode"
  degrees = "P1 Δ2 ♭3 P4 P5 Δ6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] ♭3[-6] P4[-2] P5[+2] Δ6[+6] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 16/15"
    adjustments = "P1[0] Δ2[+4] ♭3[+16] P4[-2] P5[+2] Δ6[+6] ♭7[+18]"

  [[modes.tunings]]
    name = "Harmonic 15/14"
    adjustments = "P1[0] Δ2[+4] ♭3[+23] P4[-2] P5[+2] Δ6[+6] ♭7[+25]"

  [[modes.tunings]]
    name = "Harmonic 14/13"
    adjustments = "P1[0] Δ2[+4] ♭3[+32] P4[-2] P5[+2] Δ6[+6] ♭7[+34]"

  [[modes.tunings]]
    name = "Harmonic 13/12"
    adjustments = "P1[0] Δ2[+4] ♭3[+43] P4[-2] P5[+2] Δ6[+6] ♭7[+45]"

  [[modes.tunings]]
    name = "Harmonic 10/9 (major), Neva"
    adjustments = "P1[0] Δ2[-18] ♭3[-6] P4[-2] P5[+2] Δ6[-16] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 11/10 (major), Bayati-Rast"
    adjustments = "P1[0] Δ2[-35] ♭3[-6] P4[-2] P5[+2] Δ6[-33] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 12/11 (major), Bayati-Rast"
    adjustments = "P1[0] Δ2[-49] ♭3[-6] P4[-2] P5[+2] Δ6[-47] ♭7[-4]"

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (upper octave)"
    Arabic = "Maqam Bayati-Rast"
    Turkish = "Neva Makam"
    Hindustani = "Kafi Thaat"
    Carnatic = "Kharaharapriya (22nd Mēḷakarta Rāgam)"
    Japanese = "Ritsu (aux. ♭3/♭7)"

[[modes]]
  ordinal = 5
  slug = "aeo"
  canonical = "Aeolian Mode"
  degrees = "P1 Δ2 ♭3 P4 P5 ♭6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] ♭3[-6] P4[-2] P5[+2] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 16/15"
    adjustments = "P1[0] Δ2[+4] ♭3[+16] P4[-2] P5[+2] ♭6[+14] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 15/14"
    adjustments = "P1[0] Δ2[+4] ♭3[+23] P4[-2] P5[+2] ♭6[+21] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 14/13"
    adjustments = "P1[0] Δ2[+4] ♭3[+32] P4[-2] P5[+2] ♭6[+30] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 13/12"
    adjustments = "P1[0] Δ2[+4] ♭3[+43] P4[-2] P5[+2] ♭6[+41] ♭7[-4]"

  [modes.names]
    Western = "Minor Scale, Natural Minor"
    Ashkenazi = "Magein Avot Mode"
    Arabic = "Maqam Nahawand-Kurd"
    Turkish = "Bûselik-Kurdi Makam"
    Hindustani = "Asavari Thaat"
    Carnatic = "Naṭabhairavi (20th Mēḷakarta Rāgam)"
    Japanese = "Yo (A mode, aux. 2/♭6)"

[[modes]]
  ordinal = 6
  slug = "phr"
  canonical = "Phrygian Mode"
  degrees = "P1 ♭2 ♭3 P4 P5 ♭6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] ♭2[-10] ♭3[-6] P4[-2] P5[+2] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 16/15"
    adjustments = "P1[0] ♭2[+12] ♭3[-6] P4[-2] P5[+2] ♭6[+14] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 15/14"
    adjustments = "P1[0] ♭2[+19] ♭3[-6] P4[-2] P5[+2] ♭6[+21] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 14/13"
    adjustments = "P1[0] ♭2[+28] ♭3[-6] P4[-2] P5[+2] ♭6[+30] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 13/12"
    adjustments = "P1[0] ♭2[+39] ♭3[-6] P4[-2] P5[+2] ♭6[+41] ♭7[-4]"

  [modes.names]
    Ashkenazi = "Yishtabach Mode"
    Arabic = "Maqam Kurd"
    Turkish = "Kürdî Makam"
    Hindustani = "Bhairavi Thaat"
    Carnatic = "Tōdi [Hanumatōdi] (8th Mēḷakarta Rāgam)"
    Japanese = "In (E mode, aux. ♭3/♭7)"

[[modes]]
  ordinal = 7
  slug = "loc"
  canonical = "Locrian Mode"
  degrees = "P1 ♭2 ♭3 P4 ♯4 ♭6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] ♭2[-10] ♭3[-6] P4[-2] ♯4[-12] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 16/15"
    adjustments = "P1[0] ♭2[+12] ♭3[-6] P4[-2] ♯4[+10] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 15/14"
    adjustments = "P1[0] ♭2[+19] ♭3[-6] P4[-2] ♯4[+17] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 14/13"
    adjustments = "P1[0] ♭2[+28] ♭3[-6] P4[-2] ♯4[+26] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Harmonic 13/12"
    adjustments = "P1[0] ♭2[+39] ♭3[-6] P4[-2] ♯4[+37] ♭6[-8] ♭7[-4]"

  [modes.names]
    Arabic = "Maqam Lami"
