[[modes]]
  ordinal = 1
  slug = "lyd"
  canonical = "Lydian Mode"
  degrees = "P1 Δ2 Δ3 ♯4 P5 Δ6 Δ7"

  [modes.tunings]
    major = "F G A B C D E"
    minor = "A♭ B♭ C D E♭ F G"

  [modes.names]
    Hindustani = "Kalyan Thaat"
    Carnatic = "Kaḷyāṇi (65th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. #4/7)"

[[modes]]
  ordinal = 2
  slug = "ion"
  canonical = "Ionian Mode"
  degrees = "P1 Δ2 Δ3 P4 P5 Δ6 Δ7"

  [modes.tunings]
    major = "C D E F G A B"
    minor = "E♭ F G A♭ B♭ C D"

  [modes.names]
    Western = "Major Scale"
    Arabic = "Maqam ‘Ajam"
    Turkish = "Acem/Çârgâh Makam, Rast Makam (ascending)"
    Persian = "Dastgāh-e Māhur (lower octave)"
    Hindustani = "Bilaval [Bilawal] Thaat"
    Carnatic = "Śankarābharaṇaṃ [Dhīraśankarābharaṇaṃ] (29th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/7)"

[[modes]]
  ordinal = 3
  slug = "mix"
  canonical = "Mixolydian Mode"
  degrees = "P1 Δ2 Δ3 P4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "G A B C D E F"
    minor = "B♭ C D E♭ F G A♭"

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (lower octave)"
    Turkish = "Rast Makam (descending)"
    Persian = "Dastgāh-e Māhur (upper octave)"
    Hindustani = "Khamaj Thaat"
    Carnatic = "Harikāmbhōji (28th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/♭7)"

[[modes]]
  ordinal = 4
  slug = "dor"
  canonical = "Dorian Mode"
  degrees = "P1 Δ2 ♭3 P4 P5 Δ6 ♭7"

  [modes.tunings]
    major = "D E F G A B C"
    minor = "F G A♭ B♭ C D E♭"

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (upper octave)"
    Hindustani = "Kafi Thaat"
    Carnatic = "Kharaharapriya (22nd Mēḷakarta Rāgam)"
    Japanese = "Ritsu (aux. ♭3/♭7)"

[[modes]]
  ordinal = 5
  slug = "aeo"
  canonical = "Aeolian Mode"
  degrees = "P1 Δ2 ♭3 P4 P5 ♭6 ♭7"

  [modes.tunings]
    major = "A B C D E F G"
    minor = "C D E♭ F G A♭ B♭"

  [modes.names]
    Western = "Minor Scale, Natural Minor"
    Ashkenazi = "Magein Avot Mode"
    Arabic = "Maqam Nahawand-Kurd"
    Turkish = "Bûselik-Kurdi Makam"
    Hindustani = "Asavari Thaat"
    Carnatic = "Naṭabhairavi (20th Mēḷakarta Rāgam)"
    Japanese = "Yo (A mode, aux. 2/♭6)"

[[modes]]
  ordinal = 6
  slug = "phr"
  canonical = "Phrygian Mode"
  degrees = "P1 ♭2 ♭3 P4 P5 ♭6 ♭7"

  [modes.tunings]
    major = "E F G A B C D"
    minor = "G A♭ B♭ C D E♭ F"

  [modes.names]
    Ashkenazi = "Yishtabach Mode"
    Arabic = "Maqam Kurd"
    Turkish = "Kürdî Makam"
    Hindustani = "Bhairavi Thaat"
    Carnatic = "Tōdi [Hanumatōdi] (8th Mēḷakarta Rāgam)"
    Japanese = "In (E mode, aux. ♭3/♭7)"

[[modes]]
  ordinal = 7
  slug = "loc"
  canonical = "Locrian Mode"
  degrees = "P1 ♭2 ♭3 P4 ♯4 ♭6 ♭7"

  [modes.tunings]
    major = "B C D E F G A"
    minor = "D E♭ F G A♭ B♭ C"

  [modes.names]
    Arabic = "Maqam Lami"
