[[modes]]
  ordinal = 1
  slug = "rast-from-4"
  canonical = "Rast (from IV)"
  degrees = "P1 Δ2 Δ3 ‖4 P5 Δ6 ▷7"
  tunings = [
    "F G A B▷ C D E▷",
    "G A B C‖ D E F‖",
  ]

[[modes]]
  ordinal = 2
  slug = "rast"
  canonical = "Rast"
  degrees = "P1 Δ2 ▷3 P4 P5 Δ6 ▷7"
  tunings = [
    "C D E▷ F G A B▷",
    "D E F‖ G A B C‖",
  ]

  [modes.names]
    Arabic = "Maqam Rast"

[[modes]]
  ordinal = 3
  slug = "nairuz"
  canonical = "Nairuz"
  degrees = "P1 Δ2 ▷3 P4 P5 ▷6 ♭7"
  tunings = [
    "G A B▷ C D E▷ F",
    "A B C‖ D E F‖ G",
  ]

  [modes.names]
    Arabic = "Maqam Nairuz, Maqam Yakah"

[[modes]]
  ordinal = 4
  slug = "bayati-rast"
  canonical = "Bayati-Rast"
  degrees = "P1 ▷2 ♭3 P4 P5 ▷6 ♭7"
  tunings = [
    "D E▷ F G A B▷ C",
    "E F‖ G A B C‖ D",
  ]

  [modes.names]
    Arabic = "Maqam Bayati-Rast, Maqam Muhayyar"

[[modes]]
  ordinal = 5
  slug = "bayati-rast-from-5"
  canonical = "Bayati-Rast (from V)"
  degrees = "P1 ▷2 ♭3 P4 ▷5 ♭6 ♭7"
  tunings = [
    "A B▷ C D E▷ F G",
    "B C‖ D E F‖ G A",
  ]

[[modes]]
  ordinal = 6
  slug = "sikah"
  canonical = "Sikah"
  degrees = "P1 ▷2 ▷3 ‖4 P5 ▷6 ▷7"
  tunings = [
    "E▷ F G A B▷ C D",
    "F‖ G A B C‖ D E",
  ]

  [modes.names]
    Arabic = "Maqam Sikah"

[[modes]]
  ordinal = 7
  slug = "iraq"
  canonical = "Iraq"
  degrees = "P1 ▷2 ▷3 P4 ▷5 ▷6 ▷7"
  tunings = [
    "B▷ C D E▷ F G A",
    "C‖ D E F‖ G A B",
  ]

  [modes.names]
    Arabic = "Maqam ‘Iraq"
