[[modes]]
  ordinal = 1
  slug = "lyd"
  canonical = "Lydian Mode"
  degrees = "P1 Δ2 Δ3 ‖4 P5 Δ6 ▷7"
  tunings = [
    "F G A B▷ C D E▷",
    "G A B C‖ D E F‖",
  ]

  [modes.names]

[[modes]]
  ordinal = 2
  slug = "rast"
  canonical = "Rast"
  degrees = "P1 Δ2 ▷3 P4 P5 Δ6 ▷7"
  tunings = [
    "C D E▷ F G A B▷",
    "D E F‖ G A B C‖",
  ]

  [modes.names]
    Arabic = "Maqam Rast"

[[modes]]
  ordinal = 3
  slug = "mix"
  canonical = "Mixolydian Mode"
  degrees = "P1 Δ2 ▷3 P4 P5 ▷6 ♭7"
  tunings = [
    "G A B▷ C D E▷ F",
    "A B C‖ D E F‖ G",
  ]

  [modes.names]

[[modes]]
  ordinal = 4
  slug = "dor"
  canonical = "Dorian Mode"
  degrees = "P1 ▷2 ♭3 P4 P5 ▷6 ♭7"
  tunings = [
    "D E▷ F G A B▷ C",
    "E F‖ G A B C‖ D",
  ]

  [modes.names]


[[modes]]
  ordinal = 5
  slug = "aeo"
  canonical = "Aeolian Mode"
  degrees = "P1 ▷2 ♭3 P4 ▷5 ♭6 ♭7"
  tunings = [
    "A B▷ C D E▷ F G",
    "B C‖ D E F‖ G A",
  ]

  [modes.names]


[[modes]]
  ordinal = 6
  slug = "phr"
  canonical = "Phrygian Mode"
  degrees = "P1 ▷2 ▷3 ‖4 P5 ▷6 ▷7"
  tunings = [
    "E▷ F G A B▷ C D",
    "F‖ G A B C‖ D E",
  ]

  [modes.names]

[[modes]]
  ordinal = 7
  slug = "loc"
  canonical = "Locrian Mode"
  degrees = "P1 ▷2 ▷3 P4 ▷5 ▷6 ▷7"
  tunings = [
    "B▷ C D E▷ F G A",
    "C‖ D E F‖ G A B",
  ]

  [modes.names]
