degree = 1
position = 1
pitch12 = 0
pitch24 = 0
ET = 0

[[tunings]]
limit = 1
ratio = "1/1"
cents = 0

[[tunings]]
limit = 5
ratio = "81/80"
cents = 20.51

[[tunings]]
limit = 5
ratio = "160/81"
cents = 1178.49
