degree = 3
position = 0
pitch12 = 3
pitch24 = 6
ET = 300

[[tunings]]
limit = 13
ratio = "13/11"
cents = 289.21

[[tunings]]
limit = 3
ratio = "32/37"
cents = 294.13

[[tunings]]
limit = 19
ratio = "19/16"
cents = 297.51

[[tunings]]
limit = 7
ratio = "25/21"
cents = 301.85

[[tunings]]
limit = 5
ratio = "6/5"
cents = 315.64
