degree = 3
position = 0.5
pitch24 = 7
ET = 350

[[tunings]]
limit = 17
ratio = "17/14"
cents = 336.13

[[tunings]]
limit = 5
ratio = "243/200"
cents = 337.15

[[tunings]]
limit = 11
ratio = "11/9"
cents = 347.41

[[tunings]]
limit = 13
ratio = "16/13"
cents = 359.47

[[tunings]]
limit = 5
ratio = "100/81"
cents = 364.81
