degree = 3
position = -0.5
pitch24 = 5
ET = 250

[[tunings]]
limit = 13
ratio = "15/13"
cents = 247.74

[[tunings]]
limit = 7
ratio = "7/6"
cents = 266.87

[[tunings]]
limit = 5
ratio = "75/64"
cents = 274.58
