degree = 4
position = 0
pitch12 = 5
pitch24 = 10
ET = 500

[[tunings]]
limit = 7
ratio = "21/16"
cents = 470.78

[[tunings]]
limit = 3
ratio = "4/3"
cents = 498.04

[[tunings]]
limit = 5
ratio = "27/20"
cents = 519.55
