degree = 4
position = 1
pitch12 = 6
pitch24 = 12
ET = 600

[[tunings]]
limit = 5
ratio = "45/32"
cents = 590.22

[[tunings]]
limit = 7
ratio = "7/5"
cents = 582.51

[[tunings]]
limit = 3
ratio = "729/512"
cents = 611.73
