degree = 4
position = 0.5
pitch24 = 11
ET = 550

[[tunings]]
limit = 11
ratio = "15/11"
cents = 536.95

[[tunings]]
limit = 11
ratio = "11/8"
cents = 551.32

[[tunings]]
limit = 13
ratio = "18/13"
cents = 563.38

[[tunings]]
limit = 5
ratio = "25/18"
cents = 568.72
