degree = 6
position = 0
pitch12 = 8
pitch24 = 16
ET = 800

[[tunings]]
limit = 7
ratio = "11/7"
cents = 782.49

[[tunings]]
limit = 3
ratio = "128/81"
cents = 792.18

[[tunings]]
limit = 5
ratio = "8/5"
cents = 813.69
