degree = 6
position = 0.5
pitch24 = 17
ET = 850

[[tunings]]
limit = 5
ratio = "81/50"
cents = 835.19

[[tunings]]
limit = 13
ratio = "13/8"
cents = 840.53

[[tunings]]
limit = 11
ratio = "18/11"
cents = 852.59

[[tunings]]
limit = 5
ratio = "400/243"
cents = 862.85
