degree = 6
position = -0.5
pitch24 = 15
ET = 750

[[tunings]]
limit = 5
ratio = "192/125"
cents = 743.01

[[tunings]]
limit = 7
ratio = "14/9"
cents = 764.92

[[tunings]]
limit = 5
ratio = "25/16"
cents = 772.63
