degree = 7
position = 1
pitch12 = 11
pitch24 = 22
ET = 1100

[[tunings]]
limit = 5
ratio = "15/8"
cents = 1088.27

[[tunings]]
limit = 5
ratio = "256/135"
cents = 1107.82

[[tunings]]
limit = 3
ratio = "243/128"
cents = 1109.78
