degree = 7
position = 0
pitch12 = 10
pitch24 = 20
ET = 1000

[[tunings]]
limit = 3
ratio = "16/9"
cents = 996.09

[[tunings]]
limit = 5
ratio = "9/5"
cents = 1017.60

[[tunings]]
limit = 11
ratio = "20/11"
cents = 1035

[[tunings]]
limit = 5
ratio = "729/400"
cents = 1039.1
