degree = 7
position = -0.5
pitch24 = 19
ET = 950

[[tunings]]
limit = 7
ratio = "12/7"
cents = 933.13

[[tunings]]
limit = 5
ratio = "125/72"
cents = 955.03

[[tunings]]
limit = 7
ratio = "256/147"
cents = 960.39

[[tunings]]
limit = 7
ratio = "7/4"
cents = 968.83
