[degrees]
1 = [1]
2 = []
3 = [0]
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Western = ["Minor Pentatonic", "Dorian/Aeolian/Phrygian"]
Ethiopian = ["Batti Minor"]
Korean = ["Kyemyonjo"]
Japanese = ["Yo"]
Chinese = ["Yu"]
Exoticisms = ["Peruvian Pentatonic (minor)"]

[family]
base = "ion-mix-dor"
degree = 2
