[degrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = [1]
7 = []

[names]
Western = ["Ionian/Mixolydian/Dorian"]
Korean = ["Pyongjo"]
Japanese = ["Ritsu"]
Chinese = ["Zhi"]
Ethiopian = ["Ambassel (variation)", "Anchihoye (variation)"]
Jazz = ["Blues Major (pentatonic)"]
Exoticisms = ["Scottish Pentatonic"]

[family]
base = "ion-mix-dor"
degree = 1
