[degrees]
1 = [1]
2 = []
3 = [0]
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Western = ["Minor Pentatonic"]
Ethiopian = ["Batti Minor"]
Japanese = ["Yo"]
Chinese = ["Yu"]
Exoticisms = ["Peruvian Pentatonic (minor)"]