[degrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Western = ["Mixolydian/Dorian/Aeolian"]
Ethiopian = ["Yematebela Wofe"]
Chinese = ["Shang"]
Jazz = ["Suspended Pentatonic"]
Exoticisms = ["Egyptian"]

[family]
base = "ion-mix-dor"
degree = 5
