[degrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = [1]
7 = []

[names]
Exoticisms = ["Scottish Pentatonic"]
Korean = ["Pyongjo"]
Japanese = ["Ritsu"]
Chinese = ["Zhi"]
Ethiopian = ["Ambassel (variation)", "Anchihoye (variation)"]
