[degrees]
1 = [1]
2 = [1]
3 = []
4 = [0]
5 = [1]
6 = []
7 = [0]

[names]
Ethiopian = ["Yematebela Wofe"]
Chinese = ["Shang"]
Western = ["Suspended Pentatonic", "Mixolydian/Dorian/Aeolian"]
Exoticisms = ["Egyptian"]
