limit = 7
degree = "♭3-"
ratio = "7/6"
cents = 267

[[divisions]]
  limit = 7
  degrees = ["Δ2", "♭2"]
  ratios = ["10/9", "21/20"]
  cents = [182, 84]

[[divisions]]
  limit = 7
  degrees = ["Δ2-", "♭2"]
  ratios = ["35/32", "16/15"]
  cents = [155, 112]

