limit = 5
degree = "♭3"
ratio = "6/5"
cents = 316

[[divisions]]
  limit = 5
  degrees = ["Δ2+", "♭2-"]
  ratios = ["144/125", "25/24"]
  cents = [245, 71]

[[divisions]]
  limit = 5
  degrees = ["Δ2", "♭2"]
  ratios = ["256/225", "135/128"]
  cents = [223, 92]

[[divisions]]
  limit = 5
  degrees = ["Δ2", "♭2"]
  ratios = ["9/8", "16/15"]
  cents = [204, 112]

[[divisions]]
  limit = 5
  degrees = ["Δ2", "♭2+"]
  ratios = ["10/9", "27/25"]
  cents = [182, 133]

[[divisions]]
  limit = 11
  degrees = ["Δ2-", "Δ2-"]
  ratios = ["11/10", "12/11"]
  cents = [165, 151]
