[[modes]]
  slug = "lyd-r2"
  canonical = "Lydian ↑2"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [0, 1]
    4 = [1]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Carnatic = "Kōsalam (71st Mēḷakarta Rāgam)"

[[modes]]
  slug = "ion-r5"
  canonical = "Ionian ↑5"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = []
    6 = [0, 1]
    7 = [1]
