[[modes]]
  ordinal = 1
  slug = "lyd-r2"
  canonical = "Lydian ↑2"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = []
    3 = [0, 1]
    4 = [1]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Carnatic = "Kōsalam (71st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 2
  slug = "ion-r5"
  canonical = "Ionian ↑5"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = []
    6 = [0, 1]
    7 = [1]

[[modes]]
  ordinal = 4
  slug = "dor-s4"
  canonical = "Dorian ♯4"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [1]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Western = "Ukrainian Dorian, Romanian Minor"
    Ashkenazi = "Misheberekh Mode"
    Arabic = "Maqam Nikriz"
    Carnatic = "Hēmavati (58th Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 5
  slug = "aeo-maj7"
  canonical = "Aeolian Δ7"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [0]
    7 = [1]

  [modes.names]
    Western = "Harmonic Minor"
    Arabic = "Maqam Nahawand-Hijaz"
    Turkish = "Bûselik-Hicaz Makam"
    Carnatic = "Keeravāṇi (21st Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 6
  slug = "phr-maj3"
  canonical = "Phrygian Δ3"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [0]
    7 = [0]

  [modes.names]
    Western = "Phrygian Dominant, Spanish Phrygian"
    Ashkenazi = "Ahava Rabbah Mode, Freygish"
    Iberian = "Escala Andaluza"
    Arabic = "Maqam Hijaz-Nahawand"
    Carnatic = "Vakuḷābharaṇam (14th Mēḷakarta Rāgam)"

[[modes]]
  ordinal = 7
  slug = "loc-maj6"
  canonical = "Locrian Δ6"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0, 1]
    5 = []
    6 = [1]
    7 = [0]
