[[modes]]
  ordinal = 1
  slug = "lyd"
  canonical = "Lydian Mode"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [1]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Hindustani = "Kalyan Thaat"
    Carnatic = "Kaḷyāṇi (65th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. #4/7)"

[[modes]]
  ordinal = 2
  slug = "ion"
  canonical = "Ionian Mode"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Western = "Major Scale"
    Arabic = "Maqam ‘Ajam"
    Turkish = "Çârgâh Makam, Rast Makam (ascending)"
    Persian = "Dastgāh-e Māhur (lower octave)"
    Hindustani = "Bilaval [Bilawal] Thaat"
    Carnatic = "Śankarābharaṇaṃ [Dhīraśankarābharaṇaṃ] (29th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/7)"

[[modes]]
  ordinal = 3
  slug = "mix"
  canonical = "Mixolydian Mode"
  quality = "major"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (lower octave)"
    Turkish = "Rast Makam (descending)"
    Persian = "Dastgāh-e Māhur (upper octave)"
    Hindustani = "Khamaj Thaat"
    Carnatic = "Harikāmbhōji (28th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/♭7)"

[[modes]]
  ordinal = 4
  slug = "dor"
  canonical = "Dorian Mode"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (upper octave)"
    Hindustani = "Kafi Thaat"
    Carnatic = "Kharaharapriya (22nd Mēḷakarta Rāgam)"
    Japanese = "Ritsu (aux. ♭3/♭7)"

[[modes]]
  ordinal = 5
  slug = "aeo"
  canonical = "Aeolian Mode"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [0]
    7 = [0]

    [modes.names]
      Western = "Minor Scale, Natural Minor"
      Ashkenazi = "Magein Avot Mode"
      Arabic = "Maqam Nahawand-Kurd"
      Turkish = "Bûselik-Kurdi Makam"
      Hindustani = "Asavari Thaat"
      Carnatic = "Naṭabhairavi (20th Mēḷakarta Rāgam)"
      Japanese = "Yo (A mode, aux. 2/♭6)"

[[modes]]
  ordinal = 6
  slug = "phr"
  canonical = "Phrygian Mode"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [0]
    7 = [0]

  [modes.names]
    Ashkenazi = "Yishtabach Mode"
    Arabic = "Maqam Kurd"
    Turkish = "Kürdî Makam"
    Hindustani = "Bhairavi Thaat"
    Carnatic = "Tōdi [Hanumatōdi] (8th Mēḷakarta Rāgam)"
    Japanese = "In (E mode, aux. ♭3/♭7)"

[[modes]]
  ordinal = 7
  slug = "loc"
  canonical = "Locrian Mode"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0, 1]
    5 = []
    6 = [0]
    7 = [0]

  [modes.names]
    Arabic = "Maqam Lami"
