[[modes]]
  slug = "lydian"
  canonical = "Lydian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [1]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Carnatic = "Kalyāni (Kaḷyāṇi) Rāgam"
    Hindustani = "Kalyan Thaat"

[[modes]]
  slug = "ionian"
  canonical = "Ionian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Western = "Major Scale"
    Carnatic = "Shankarābharanam (Śankarābharaṇaṃ, Dhīraśankarābharaṇaṃ) Rāgam"
    Hindustani = "Bilaval (Bilawal) Thaat"
    Persian = "Dastgāh-e Māhur"
    Turkish = "Çargah (Çârgâh) Makam, Rast Makam (ascending)"
    Arabic = "Maqam ‘Ajam"

[[modes]]
  slug = "mixolydian"
  canonical = "Mixolydian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Carnatic = "Harikāmbhōji Rāgam"
    Hindustani = "Khamaj Thaat"
    Turkish = "Rast Makam (descending)"

[[modes]]    
  slug = "dorian"
