[[modes]]
  ordinal = 1
  slug = "lyd"
  canonical = "Lydian Mode"
  degrees = "P1 Δ2 Δ3 ♯4 P5 Δ6 Δ7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] ♯4[+12] P5[+2] Δ6[+6] Δ7[+10]"

  [[modes.tunings]]
    name = "Just Thirds (major) / Yaman"
    adjustments = "P1[0] Δ2[+4] Δ3[-14] ♯4[-10] P5[+2] Δ6[+6] Δ7[-12]"

  [modes.names]
    Hindustani = "Kalyan Thaat, Raag Yaman"
    Carnatic = "Kaḷyāṇi (65th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. #4/7)"

[[modes]]
  ordinal = 2
  slug = "ion"
  canonical = "Ionian Mode"
  degrees = "P1 Δ2 Δ3 P4 P5 Δ6 Δ7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] P4[-2] P5[+2] Δ6[+6] Δ7[+10]"

  [[modes.tunings]]
    name = "Just Thirds (major) / Bilaval"
    adjustments = "P1[0] Δ2[+4] Δ3[-14] P4[-2] P5[+2] Δ6[-16] Δ7[-12]"

  [modes.names]
    Western = "Major Scale"
    Arabic = "Maqam ‘Ajam"
    Turkish = "Çârgâh Makam, Rast Makam (ascending)"
    Persian = "Dastgāh-e Māhur (lower octave)"
    Hindustani = "Bilaval [Bilawal] Thaat"
    Carnatic = "Śankarābharaṇaṃ [Dhīraśankarābharaṇaṃ] (29th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/7)"

[[modes]]
  ordinal = 3
  slug = "mix"
  canonical = "Mixolydian Mode"
  degrees = "P1 Δ2 Δ3 P4 P5 Δ6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] Δ3[+8] P4[-2] P5[+2] Δ6[+6] Δ7[-4]"

  [[modes.tunings]]
    name = "Just Thirds (major)"
    adjustments = "P1[0] Δ2[-18] Δ3[-14] P4[-2] P5[+2] Δ6[-16] ♭7[-4]"

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (lower octave)"
    Turkish = "Rast Makam (descending)"
    Persian = "Dastgāh-e Māhur (upper octave)"
    Hindustani = "Khamaj Thaat"
    Carnatic = "Harikāmbhōji (28th Mēḷakarta Rāgam)"
    Japanese = "Ryo (aux. 4/♭7)"

[[modes]]
  ordinal = 4
  slug = "dor"
  canonical = "Dorian Mode"
  degrees = "P1 Δ2 ♭3 P4 P5 Δ6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] ♭3[-6] P4[-2] P5[+2] Δ6[+6] ♭7[-4]"

  [[modes.tunings]]
    name = "Kafi"
    adjustments = "P1[0] Δ2[+4] ♭3[-6] P4[-2] P5[+2] Δ6[-16] ♭7[-4]"

  [[modes.tunings]]
    name = "Just Thirds (minor)"
    adjustments = "P1[0] Δ2[+4] ♭3[+16] P4[-2] P5[+2] Δ6[+6] ♭7[+18]"

  [[modes.tunings]]
    name = "Just Thirds (major)"
    adjustments = "P1[0] Δ2[-18] ♭3[-6] P4[-2] P5[-20] Δ6[-16] ♭7[-4]"

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (upper octave)"
    Hindustani = "Kafi Thaat"
    Carnatic = "Kharaharapriya (22nd Mēḷakarta Rāgam)"
    Japanese = "Ritsu (aux. ♭3/♭7)"

[[modes]]
  ordinal = 5
  slug = "aeo"
  canonical = "Aeolian Mode"
  degrees = "P1 Δ2 ♭3 P4 P5 ♭6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] Δ2[+4] ♭3[-6] P4[-2] P5[+2] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Darabari"
    adjustments = "P1[0] Δ2[-18] ♭3[-6] P4[-2] P5[+2] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Just Thirds (minor)"
    adjustments = "P1[0] Δ2[+4] ♭3[+16] P4[-2] P5[+2] ♭6[+14] ♭7[-4]"

  [[modes.tunings]]
    name = "Just Thirds (major)"
    adjustments = "P1[0] Δ2[+4] ♭3[+16] P4[+20] P5[+2] ♭6[+14] ♭7[+18]"

  [modes.names]
    Western = "Minor Scale, Natural Minor"
    Ashkenazi = "Magein Avot Mode"
    Arabic = "Maqam Nahawand-Kurd"
    Turkish = "Bûselik-Kurdi Makam"
    Hindustani = "Asavari Thaat, Raag Darabari"
    Carnatic = "Naṭabhairavi (20th Mēḷakarta Rāgam)"
    Japanese = "Yo (A mode, aux. 2/♭6)"

[[modes]]
  ordinal = 6
  slug = "phr"
  canonical = "Phrygian Mode"
  degrees = "P1 ♭2 ♭3 P4 P5 ♭6 ♭7"

  [[modes.tunings]]
    name = "Pythagorean"
    adjustments = "P1[0] ♭2[-10] ♭3[-6] P4[-2] P5[+2] ♭6[-8] ♭7[-4]"

  [[modes.tunings]]
    name = "Just Thirds (minor)"
    adjustments = "P1[0] ♭2[+12] ♭3[-6] P4[-2] P5[+2] ♭6[+14] ♭7[+18]"

  [[modes.tunings]]
    name = "Just Thirds (major)"
    adjustments = "P1[0] ♭2[+12] ♭3[+16] P4[-2] P5[+2] ♭6[+14] ♭7[+18]"

  [[modes.tunings]]
    name = "Bhairavi"
    adjustments = "P1[0] ♭2[+12] ♭3[+16] P4[+20] P5[+2] ♭6[+14] ♭7[+18]"

  [modes.names]
    Ashkenazi = "Yishtabach Mode"
    Arabic = "Maqam Kurd"
    Turkish = "Kürdî Makam"
    Hindustani = "Bhairavi Thaat"
    Carnatic = "Tōdi [Hanumatōdi] (8th Mēḷakarta Rāgam)"
    Japanese = "In (E mode, aux. ♭3/♭7)"

[[modes]]
  ordinal = 7
  slug = "loc"
  canonical = "Locrian Mode"
  quality = "minor"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0, 1]
    5 = []
    6 = [0]
    7 = [0]

  [modes.names]
    Arabic = "Maqam Lami"
