[[modes]]
  slug = "lydian"
  canonical = "Lydian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [1]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Hindustani = "Kalyan Thaat"
    Carnatic = "Kaḷyāṇi (65th Mēḷakarta Rāgam)"
    Japanese = "Ryo (auxiliary #4/7)"

[[modes]]
  slug = "ionian"
  canonical = "Ionian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Western = "Major Scale"
    Arabic = "Maqam ‘Ajam"
    Turkish = "Çârgâh Makam, Rast Makam (ascending)"
    Persian = "Dastgāh-e Māhur (lower octave)"
    Hindustani = "Bilaval [Bilawal] Thaat"
    Carnatic = "Śankarābharaṇaṃ [Dhīraśankarābharaṇaṃ] (29th Mēḷakarta Rāgam)"
    Japanese = "Ryo (auxiliary 4/7)"

[[modes]]
  slug = "mixolydian"
  canonical = "Mixolydian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (lower octave)"
    Turkish = "Rast Makam (descending)"
    Persian = "Dastgāh-e Māhur (upper octave)"
    Hindustani = "Khamaj Thaat"
    Carnatic = "Harikāmbhōji (28th Mēḷakarta Rāgam)"
    Japanese = "Ryo (auxiliary 4/b7)"

[[modes]]
  slug = "dorian"
  canonical = "Dorian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Ashkenazi = "Adonai Malach Mode (upper octave)"
    Hindustani = "Kafi Thaat"
    Carnatic = "Kharaharapriya (22nd Mēḷakarta Rāgam)"
    Japanese = "Ritsu (auxiliary b3/b7)"

[[modes]]
  slug = "aeolian"
  canonical = "Aeolian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [0]
    7 = [0]

    [modes.names]
      Western = "Minor Scale, Natural Minor"
      Ashkenazi = "Magein Avot Mode"
      Arabic = "Maqam Nahawand-Kurd"
      Turkish = "Bûselik-Kurdi Makam"
      Hindustani = "Asavari Thaat"
      Carnatic = "Naṭabhairavi (20th Mēḷakarta Rāgam)"
      Japanese = "Yo (minor mode, auxiliary 2/b6)"

[[modes]]
  slug = "phrygian"
  canonical = "Phrygian Mode"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Ashkenazi = "Yishtabach Mode"
    Arabic = "Maqam Kurd"
    Turkish = "Kürdî Makam"
    Hindustani = "Bhairavi Thaat"
    Carnatic = "Tōdi [Hanumatōdi] (8th Mēḷakarta Rāgam)"
    Japanese = "In (primary mode, auxiliary b3/b7)"

[[modes]]
  slug = "locrian"
  canonical = "Locrian Mode"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0, 1]
    5 = []
    6 = [0]
    7 = [0]

  [modes.names]
    Arabic = "Maqam Lami"
