[[modes]]
  slug = "lydian"
  canonical = "Lydian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [1]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Carnatic = "Kalyāni [Kaḷyāṇi] Rāgam (65th Mēlakarta)"
    Hindustani = "Kalyan Thaat"
    Japanese = "Ryo (auxiliary #4/7)"

[[modes]]
  slug = "ionian"
  canonical = "Ionian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [1]

  [modes.names]
    Western = "Major Scale"
    Carnatic = "Shankarābharanam [Śankarābharaṇaṃ, Dhīraśankarābharaṇaṃ] Rāgam (29th Mēlakarta)"
    Hindustani = "Bilaval [Bilawal] Thaat"
    Persian = "Dastgāh-e Māhur (lower octave)"
    Turkish = "Çargah [Çârgâh] Makam, Rast Makam (ascending)"
    Arabic = "Maqam ‘Ajam"
    Japanese = "Ryo (auxiliary 4/7)"

[[modes]]
  slug = "mixolydian"
  canonical = "Mixolydian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [1]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Carnatic = "Harikāmbhōji Rāgam (28th Mēlakarta)"
    Hindustani = "Khamaj Thaat"
    Persian = "Dastgāh-e Māhur (upper octave)"
    Turkish = "Rast Makam (descending)"
    Jewish = "Adonai Malach Mode (lower octave)"
    Japanese = "Ryo (auxiliary 4/b7)"

[[modes]]
  slug = "dorian"
  canonical = "Dorian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Carnatic = "Kharaharapriya Rāgam (22nd Mēlakarta)"
    Hindustani = "Kafi Thaat"
    Jewish = "Adonai Malach Mode (upper octave)"
    Japanese = "Ritsu (auxiliary b3/b7)"

[[modes]]
  slug = "aeolian"
  canonical = "Aeolian Mode"

  [modes.degrees]
    1 = [1]
    2 = [1]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [0]
    7 = [0]

    [modes.names]
      Western = "Minor Scale, Natural Minor"
      Carnatic = "Natabhairavi [Naṭabhairavi] Rāgam (20th Mēlakarta)"
      Hindustani = "Asavari Thaat"
      Turkish = "Buselik [Bûselik] Makam"
      Arabic = "Maqam Nahawand-Kurd"
      Jewish = "Magein Avot Mode"
      Japanese = "Yo (minor mode, auxiliary 2/b6)"

[[modes]]
  slug = "phrygian"
  canonical = "Phrygian Mode"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0]
    5 = [1]
    6 = [1]
    7 = [0]

  [modes.names]
    Carnatic = "Tōdi [Hanumatōdi] Rāgam (8th Mēlakarta)"
    Hindustani = "Bhairavi Thaat"
    Turkish = "Kurdi [Kürdî] Makam"
    Arabic = "Maqam Kurd"
    Jewish = "Yishtabach Mode"
    Japanese = "In (primary mode, auxiliary b3/b7)"

[[modes]]
  slug = "locrian"
  canonical = "Locrian Mode"

  [modes.degrees]
    1 = [1]
    2 = [0]
    3 = [0]
    4 = [0, 1]
    5 = []
    6 = [0]
    7 = [0]

  [modes.names]
    Arabic = "Maqam Lami"
