[[notes]]
  degree = "P1"
  name = "C"
  ratio = "1/1"
  cents = 0

[[notes]]
  degree = "P1[+49]"
  name = "C‖"
  ratio = "36/35"
  cents = 48.77

[[notes]]
  degree = "♭2[-20]"
  name = "C♯"
  ratio = "135/128"
  cents = 92.18

[[notes]]
  degree = "♭2"
  name = "D♭"
  ratio = "16/15"
  cents = 111.73

[[notes]]
  degree = "Δ2"
  name = "D"
  ratio = "9/8"
  cents = 203.91

[[notes]]
  degree = "♭3"
  name = "E♭"
  ratio = "6/5"
  cents = 315.64

[[notes]]
  degree = "▷3"
  name = "E▷"
  ratio = "16/13"
  cents = 359.47

[[notes]]
  degree = "Δ3"
  name = "E"
  ratio = "5/4"
  cents = 386.31

[[notes]]
  degree = "P4"
  name = "F"
  ratio = "4/3"
  cents = 498.04

[[notes]]
  degree = "‖4"
  name = "F‖"
  ratio = "18/13"
  cents = 563.38

[[notes]]
  degree = "♯4"
  name = "F♯"
  ratio = "45/32"
  cents = 590.22

[[notes]]
  degree = "♯4[+20]"
  name = "G♭"
  ratio = "64/45"
  cents = 609.78

[[notes]]
  degree = "P5"
  name = "G"
  ratio = "3/2"
  cents = 701.96

[[notes]]
  degree = "♭6"
  name = "A♭"
  ratio = "8/5"
  cents = 813.69

[[notes]]
  degree = "Δ6[+22]"
  name = "A"
  ratio = "27/16"
  cents = 905.87

[[notes]]
  degree = "♭7[+22]"
  name = "B♭"
  ratio = "9/5"
  cents = 1017.60

[[notes]]
  degree = "▷7"
  name = "B▷"
  ratio = "24/13"
  cents = 1061.43

[[notes]]
  degree = "Δ7"
  name = "B"
  ratio = "15/8"
  cents = 1088.27
