[[notes]]
  degree = "P1"
  name = "D"
  ratio = "1/1"
  cents = 0

[[notes]]
  degree = "♭2"
  name = "E♭"
  ratio = "16/15"
  cents = 111.73

[[notes]]
  degree = "▷2"
  name = "E▷"
  ratio = "128/117"
  cents = 155.56

[[notes]]
  degree = "Δ2"
  name = "E"
  ratio = "10/9"
  cents = 182.40

[[notes]]
  degree = "♭3[-22]"
  name = "F"
  ratio = "32/27"
  cents = 294.13

[[notes]]
  degree = "▷3[-16]"
  name = "F‖"
  ratio = "128/105"
  cents = 342.90

[[notes]]
  degree = "Δ3"
  name = "F♯"
  ratio = "5/4"
  cents = 386.31

[[notes]]
  degree = "Δ3[+22]"
  name = "G♭"
  ratio = "81/64"
  cents = 407.82

[[notes]]
  degree = "P4"
  name = "G"
  ratio = "4/3"
  cents = 498.04

[[notes]]
  degree = "♯4[+20]"
  name = "A♭"
  ratio = "64/45"
  cents = 609.78

[[notes]]
  degree = "P5"
  name = "A"
  ratio = "3/2"
  cents = 701.96

[[notes]]
  degree = "♭6"
  name = "B♭"
  ratio = "8/5"
  cents = 813.69

[[notes]]
  degree = "▷6"
  name = "B▷"
  ratio = "64/39"
  cents = 857.52

[[notes]]
  degree = "Δ6"
  name = "B"
  ratio = "5/3"
  cents = 884.36

[[notes]]
  degree = "♭7"
  name = "C"
  ratio = "16/9"
  cents = 996.09

[[notes]]
  degree = "▷7"
  name = "C‖"
  ratio = "24/13"
  cents = 1061.43

[[notes]]
  degree = "Δ7"
  name = "C♯"
  ratio = "15/8"
  cents = 1088.27

[[notes]]
  degree = "Δ7[+20]"
  name = "D♭"
  ratio = "256/135"
  cents = 1107.82
