[[notes]]
  degree = "♭2"
  name = "A♭"
  ratio = "16/15"
  cents = 111.73

[[notes]]
  degree = "♭3"
  name = "B♭"
  ratio = "6/5"
  cents = 315.64

[[notes]]
  degree = "♭5"
  name = "D♭"
  ratio = "64/45"
  cents = 609.78

[[notes]]
  degree = "♭6"
  name = "E♭"
  ratio = "8/5"
  cents = 813.69

[[notes]]
  degree = "♭8"
  name = "G♭"
  ratio = "48/25"
  cents = 1129.33
