[[notes]]
  degree = "▷2"
  name = "A▷"
  ratio = "35/32"
  cents = 155.14

[[notes]]
  degree = "▷3"
  name = "B▷"
  ratio = "16/13"
  cents = 359.47

[[notes]]
  degree = "▷5"
  name = "D▷"
  ratio = "35/24"
  cents = 653.18

[[notes]]
  degree = "▷6"
  name = "E▷"
  ratio = "64/39"
  cents = 857.52

[[notes]]
  degree = "▷8"
  name = "G▷"
  ratio = "35/18"
  cents = 1151.23
