[[notes]]
  degree = "‖1"
  name = "G‖"
  ratio = "40/39"
  cents = 43.83

[[notes]]
  degree = "‖2"
  name = "A‖"
  ratio = "15/13"
  cents = 247.74

[[notes]]
  degree = "‖4"
  name = "C‖"
  ratio = "15/11"
  cents = 536.95

[[notes]]
  degree = "‖5"
  name = "D‖"
  ratio = "20/13"
  cents = 745.79

[[notes]]
  degree = "▷7"
  name = "F‖"
  ratio = "20/11"
  cents = 1035.00
