

[[notes]]
  degree = "▷2₋"
  name = "A▷₋"
  ratio = "13/12"
  cents = 138.57

[[notes]]
  degree = "▷2"
  name = "A▷"
  ratio = "35/32"
  cents = 155.14

[[notes]]
  degree = "▷2₊"
  name = "A▷₊"
  ratio = "11/10"
  cents = 165.00

[[notes]]
  degree = "▷3₋"
  name = "B▷₋"
  ratio = "17/14"
  cents = 336.13

[[notes]]
  degree = "▷3"
  name = "B▷"
  ratio = "39/32"
  cents = 342.48

[[notes]]
  degree = "▷3₊"
  name = "B▷₊"
  ratio = "16/13"
  cents = 359.47

[[notes]]
  degree = "▷5₋"
  name = "D▷₋"
  ratio = "13/9"
  cents = 636.62

[[notes]]
  degree = "▷5"
  name = "D▷"
  ratio = "35/24"
  cents = 653.18

[[notes]]
  degree = "▷5₊"
  name = "D▷₊"
  ratio = "22/15"
  cents = 663.05

[[notes]]
  degree = "▷6₋"
  name = "E▷"
  ratio = "34/21"
  cents = 834.17

[[notes]]
  degree = "▷6₋"
  name = "E▷"
  ratio = "13/8"
  cents = 840.53

[[notes]]
  degree = "▷6₊"
  name = "E▷₊"
  ratio = "64/39"
  cents = 857.52
