[[notes]]
  degree = "P1"
  name = "A"
  ratio = "1/1"
  cents = 0

[[notes]]
  degree = "Δ2"
  name = "B"
  ratio = "10/9"
  cents = 182.40

[[notes]]
  degree = "♭3"
  name = "C"
  ratio = "6/5"
  cents = 315.64

[[notes]]
  degree = "P4"
  name = "D"
  ratio = "4/3"
  cents = 498.04

[[notes]]
  degree = "P5"
  name = "E"
  ratio = "40/27"
  cents = 680.45

[[notes]]
  degree = "♭6"
  name = "F"
  ratio = "128/81"
  cents = 792.81

[[notes]]
  degree = "♭7"
  name = "G"
  ratio = "16/9"
  cents = 996.09
