limit = 7
degree = "P4"
ratio = "21/16"
cents = 471

[[divisions]]
  limit = 7
  degrees = ["Δ3", "♭2"]
  ratios = ["5/4", "21/20"]
  cents = [386, 84]

[[divisions]]
  limit = 7
  degrees = ["♭3", "Δ2-"]
  ratios = ["6/5", "35/32"]
  cents = [316, 155]

[[divisions]]
  limit = 7
  degrees = ["♭3", "Δ2"]
  ratios = ["189/160", "10/9"]
  cents = [289, 182]

[[divisions]]
  limit = 7
  degrees = ["♭3-", "Δ2"]
  ratios = ["7/6", "9/8"]
  cents = [267, 204]
