limit = 3
degree = "P4"
ratio = "4/3"
cents = 498

[[divisions]]
  limit = 5
  degrees = ["Δ3+", "♭2-"]
  ratios = ["32/25", "25/24"]
  cents = [427, 71]

[[divisions]]
  limit = 3
  degrees = ["Δ3", "♭2"]
  ratios = ["81/84", "256/243"]
  cents = [408, 90]

[[divisions]]
  limit = 5
  degrees = ["Δ3", "♭2"]
  ratios = ["5/4", "16/15"]
  cents = [386, 112]

[[divisions]]
  limit = 5
  degrees = ["Δ3-", "♭2+"]
  ratios = ["100/81", "27/25"]
  cents = [365, 133]

[[divisions]]
  limit = 7
  degrees = ["♭3+", "Δ2-"]
  ratios = ["128/105", "35/32"]
  cents = [343, 155]

[[divisions]]
  limit = 5
  degrees = ["♭3+", "Δ2-"]
  ratios = ["243/200", "800/729"]
  cents = [337, 161]

[[divisions]]
  limit = 5
  degrees = ["♭3", "Δ2"]
  ratios = ["6/5", "10/9"]
  cents = [316, 182]

[[divisions]]
  limit = 3
  degrees = ["♭3", "Δ2"]
  ratios = ["32/27", "9/8"]
  cents = [294, 204]

[[divisions]]
  limit = 5
  degrees = ["♭3-", "Δ2"]
  ratios = ["75/64", "256/225"]
  cents = [275, 223]

[[divisions]]
  limit = 7
  degrees = ["♭3-", "Δ2+""]
  ratios = ["7/6", "8/7"]
  cents = [267, 231]

[[divisions]]
  limit = 5
  degrees = ["♭3-", "Δ2+"]
  ratios = ["125/108", "144/125"]
  cents = [253, 245]
