degree = 2
position = 0.5

[ET]
ratio = "2^(3/24)"
cents = 150

[L5]
ratio = "27/25"
cents = 133

[L7]
ratio = "35/32"
cents = 155

[L11]
ratio = "11/10"
cents = 165

[L13]
ratio = "13/12"
cents = 139
