degree = 3
position = 0.5

[ET]
ratio = "2^(7/24)"
cents = 350

[L5]
ratio = "100/81"
cents = 365

[L7]
ratio = "128/105"
cents = 343

[L11]
ratio = "11/9"
cents = 347

[L13]
ratio = "16/13"
cents = 359

[L17]
ratio = "17/14"
cents = 336
