degree = 3
position = 1.5

[ET]
ratio = "2^(9/24)"
cents = 450

[L5]
ratio = "32/25"
cents = 427

[L7]
ratio = "9/7"
cents = 435

[L11]
ratio = "128/99"
cents = 444

[L13]
ratio = "13/10"
cents = 454
